/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package modelsasservice

import (
	componentApi "github.com/opendatahub-io/opendatahub-operator/v2/api/components/v1alpha1"
	"github.com/opendatahub-io/opendatahub-operator/v2/internal/controller/status"
	odhtypes "github.com/opendatahub-io/opendatahub-operator/v2/pkg/controller/types"
	"github.com/opendatahub-io/opendatahub-operator/v2/pkg/deploy"
)

const (
	ComponentName = componentApi.ModelsAsServiceComponentName

	ReadyConditionType = componentApi.ModelsAsServiceKind + status.ReadySuffix

	// Default Gateway values as specified in the spec.
	DefaultGatewayNamespace = "openshift-ingress"
	DefaultGatewayName      = "maas-default-gateway"

	// Manifest paths.
	BaseManifestsSourcePath = "overlays/odh"

	// GatewayDefaultAuthPolicyName is the name of the AuthPolicy resource that configures
	// authentication for the MaaS gateway. This resource needs to be deployed to
	// the same namespace as the gateway it targets.
	GatewayDefaultAuthPolicyName = "gateway-default-auth"

	// Same but for token rate limit.
	GatewayTokenRateLimitDefaultDenyPolicyName = "gateway-default-deny"

	// MaaSAPIAuthPolicyName is the name of the AuthPolicy that configures
	// authentication for the maas-api HTTPRoute (API keys, OpenShift, optional OIDC).
	MaaSAPIAuthPolicyName = "maas-api-auth-policy"

	// GatewayDestinationRuleName is the name of the DestinationRule resource that
	// configures TLS for the MaaS gateway. This resource needs to be deployed to
	// the same namespace as the gateway it targets.
	GatewayDestinationRuleName = "maas-api-backend-tls"

	// TelemetryPolicyName is the name of the TelemetryPolicy resource that
	// configures metric labels for the MaaS gateway. This resource needs to be
	// deployed to the same namespace as the gateway it targets.
	TelemetryPolicyName = "maas-telemetry"

	// IstioTelemetryName is the default name of the Istio Telemetry resource that
	// configures per-subscription latency tracking. This resource needs to be
	// deployed to the same namespace as the gateway it targets.
	IstioTelemetryName = "latency-per-subscription"

	// MaaSParametersConfigMapName is the name of the ConfigMap that stores
	// MaaS configuration parameters (generated by kustomize from params.env).
	MaaSParametersConfigMapName = "maas-parameters"

	// MaaSAPIDeploymentName is the name of the maas-api Deployment.
	MaaSAPIDeploymentName = "maas-api"

	// MaaSDBSecretName is the name of the Secret containing the database connection URL.
	MaaSDBSecretName = "maas-db-config" //nolint:gosec // secret name reference, not a credential

	// MaaSDBSecretKey is the key within the DB config Secret that holds the connection URL.
	MaaSDBSecretKey = "DB_CONNECTION_URL"

	// MonitoringNamespace is the namespace where cluster monitoring configuration is stored.
	MonitoringNamespace = "openshift-monitoring"

	// ClusterMonitoringConfigName is the name of the ConfigMap for cluster monitoring configuration.
	ClusterMonitoringConfigName = "cluster-monitoring-config"
)

var (
	// Image parameter mappings for manifest substitution.
	imagesMap = map[string]string{
		"maas-api-image":           "RELATED_IMAGE_ODH_MAAS_API_IMAGE",
		"maas-controller-image":    "RELATED_IMAGE_ODH_MAAS_CONTROLLER_IMAGE",
		"payload-processing-image": "RELATED_IMAGE_ODH_AI_GATEWAY_PAYLOAD_PROCESSING_IMAGE",
	}

	// Additional parameters for manifest customization.
	extraParamsMap = map[string]string{
		"gateway-namespace": DefaultGatewayNamespace,
		"gateway-name":      DefaultGatewayName,
	}

	conditionTypes = []string{
		status.ConditionDependenciesAvailable,
		status.ConditionMaaSPrerequisitesAvailable,
		status.ConditionDeploymentsAvailable,
	}
)

func baseManifestInfo(sourcePath string) odhtypes.ManifestInfo {
	return odhtypes.ManifestInfo{
		Path:       deploy.DefaultManifestPath,
		ContextDir: "maas",
		SourcePath: sourcePath,
	}
}
