---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maas-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - maas.opendatahub.io
  resources:
  - maasmodelrefs
  - externalmodels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inference.opendatahub.io
  resources:
  - externalproviders
  - externalmodels
  verbs:
  - get
  - list
  - watch
