apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default

patches:
- path: remove_probes.yaml
- path: disable_leader_election.yaml
- path: override_entrypoint.yaml
- path: increase_resources.yaml
