apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-registry-operator-controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        ca:
          configMap:
            name: openshift-service-ca.crt
            key: service-ca.crt
        serverName: controller-manager-metrics-service.NAMESPACE.svc
