---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ogx-io-v1beta1-ogxserver
  failurePolicy: Fail
  name: vogxserver.kb.io
  rules:
  - apiGroups:
    - ogx.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ogxservers
  sideEffects: None
