apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml
- configmap.yaml

images:
- name: controller
  newName: quay.io/opendatahub/odh-ogx-module-operator
  newTag: odh-stable
