apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: controller-manager-pdb
  namespace: system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
       app.kubernetes.io/name: ogx-k8s-operator
