apiVersion: components.platform.opendatahub.io/v1alpha1
kind: AIGateway
metadata:
  labels:
    app.kubernetes.io/name: ai-gateway-operator
    app.kubernetes.io/managed-by: kustomize
  name: default-aigateway
spec:
  batchGateway:
    managementState: Managed
  modelsAsAService:
    managementState: Removed
