apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ .InstrumentationName }}
  namespace: {{ .Namespace }}
spec:
  exporter:
    endpoint: {{ .OtlpEndpoint }}
  sampler:
    type: traceidratio
    argument: "{{ .SampleRatio }}"
