---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: namespace-restricted-metrics-ingress
  namespace: {{.Namespace}}
  labels:
    platform.opendatahub.io/part-of: monitoring
  ownerReferences:
    - apiVersion: {{.Component.APIVersion}}
      kind: {{.Component.Kind}}
      name: {{.Component.Name}}
      uid: {{.Component.UID}}
spec:
  podSelector:
    matchLabels:
      app: namespace-restricted-metrics
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8443
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: data-science-monitoringstack
              app.kubernetes.io/component: alertmanager
      ports:
        - protocol: TCP
          port: 8443
