---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-web-tls-ca
  namespace: {{.Namespace}}
  labels:
    platform.opendatahub.io/part-of: monitoring
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operated
  namespace: {{.Namespace}}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: prometheus-operated-tls
