apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: {{ .TempoName }}
  namespace: {{ .Namespace }}
spec:
  multitenancy:
    enabled: true  # Required for OpenShift
  storage:
    traces:
      backend: {{ .Backend }}
      {{- if ne .Backend "pv" }}
      secret:
        name: {{ .Secret }}
        type: {{ .Backend }}
      {{- end }}
      {{- if and (eq .Backend "pv") .Size }}
      size: "{{ .Size }}"
      {{- end }}