apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "workbenches-operator.serviceAccountName" . }}
  namespace: {{ .Values.operatorNamespace | quote }}
  labels:
    {{- include "workbenches-operator.labels" . | nindent 4 }}
