{{- if .Values.webhooks.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "workbenches-operator.webhookServiceName" . }}
  namespace: {{ .Values.operatorNamespace | quote }}
  labels:
    {{- include "workbenches-operator.labels" . | nindent 4 }}
  {{- if eq .Values.webhooks.tlsProvider "openshift" }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "workbenches-operator.webhookCertSecret" . }}
  {{- end }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: {{ .Values.webhooks.port }}
  selector:
    {{- include "workbenches-operator.selectorLabels" . | nindent 4 }}
{{- end }}
