apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../instance

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: payload-processing
  - target:
      kind: Service
      name: payload-processing
    patch: |-
      - op: replace
        path: /metadata/name
        value: payload-pre-processing
      - op: replace
        path: /spec/selector/app
        value: payload-pre-processing
  - target:
      kind: DestinationRule
      name: payload-processing
    patch: |-
      - op: replace
        path: /metadata/name
        value: payload-pre-processing
      - op: replace
        path: /spec/host
        value: payload-pre-processing.openshift-ingress.svc.cluster.local
