//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoWorkflowsControllersSpec) DeepCopyInto(out *ArgoWorkflowsControllersSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoWorkflowsControllersSpec.
func (in *ArgoWorkflowsControllersSpec) DeepCopy() *ArgoWorkflowsControllersSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoWorkflowsControllersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeFlare) DeepCopyInto(out *CodeFlare) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeFlare.
func (in *CodeFlare) DeepCopy() *CodeFlare {
	if in == nil {
		return nil
	}
	out := new(CodeFlare)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeFlare) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeFlareCommonSpec) DeepCopyInto(out *CodeFlareCommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeFlareCommonSpec.
func (in *CodeFlareCommonSpec) DeepCopy() *CodeFlareCommonSpec {
	if in == nil {
		return nil
	}
	out := new(CodeFlareCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeFlareCommonStatus) DeepCopyInto(out *CodeFlareCommonStatus) {
	*out = *in
	in.ComponentReleaseStatus.DeepCopyInto(&out.ComponentReleaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeFlareCommonStatus.
func (in *CodeFlareCommonStatus) DeepCopy() *CodeFlareCommonStatus {
	if in == nil {
		return nil
	}
	out := new(CodeFlareCommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeFlareList) DeepCopyInto(out *CodeFlareList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CodeFlare, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeFlareList.
func (in *CodeFlareList) DeepCopy() *CodeFlareList {
	if in == nil {
		return nil
	}
	out := new(CodeFlareList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeFlareList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeFlareSpec) DeepCopyInto(out *CodeFlareSpec) {
	*out = *in
	in.CodeFlareCommonSpec.DeepCopyInto(&out.CodeFlareCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeFlareSpec.
func (in *CodeFlareSpec) DeepCopy() *CodeFlareSpec {
	if in == nil {
		return nil
	}
	out := new(CodeFlareSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeFlareStatus) DeepCopyInto(out *CodeFlareStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.CodeFlareCommonStatus.DeepCopyInto(&out.CodeFlareCommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeFlareStatus.
func (in *CodeFlareStatus) DeepCopy() *CodeFlareStatus {
	if in == nil {
		return nil
	}
	out := new(CodeFlareStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCCodeFlare) DeepCopyInto(out *DSCCodeFlare) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.CodeFlareCommonSpec.DeepCopyInto(&out.CodeFlareCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCCodeFlare.
func (in *DSCCodeFlare) DeepCopy() *DSCCodeFlare {
	if in == nil {
		return nil
	}
	out := new(DSCCodeFlare)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCCodeFlareStatus) DeepCopyInto(out *DSCCodeFlareStatus) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	if in.CodeFlareCommonStatus != nil {
		in, out := &in.CodeFlareCommonStatus, &out.CodeFlareCommonStatus
		*out = new(CodeFlareCommonStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCCodeFlareStatus.
func (in *DSCCodeFlareStatus) DeepCopy() *DSCCodeFlareStatus {
	if in == nil {
		return nil
	}
	out := new(DSCCodeFlareStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCDashboard) DeepCopyInto(out *DSCDashboard) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.DashboardCommonSpec.DeepCopyInto(&out.DashboardCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCDashboard.
func (in *DSCDashboard) DeepCopy() *DSCDashboard {
	if in == nil {
		return nil
	}
	out := new(DSCDashboard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCDashboardStatus) DeepCopyInto(out *DSCDashboardStatus) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	if in.DashboardCommonStatus != nil {
		in, out := &in.DashboardCommonStatus, &out.DashboardCommonStatus
		*out = new(DashboardCommonStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCDashboardStatus.
func (in *DSCDashboardStatus) DeepCopy() *DSCDashboardStatus {
	if in == nil {
		return nil
	}
	out := new(DSCDashboardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCDataSciencePipelines) DeepCopyInto(out *DSCDataSciencePipelines) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.DataSciencePipelinesCommonSpec.DeepCopyInto(&out.DataSciencePipelinesCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCDataSciencePipelines.
func (in *DSCDataSciencePipelines) DeepCopy() *DSCDataSciencePipelines {
	if in == nil {
		return nil
	}
	out := new(DSCDataSciencePipelines)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCDataSciencePipelinesStatus) DeepCopyInto(out *DSCDataSciencePipelinesStatus) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	if in.DataSciencePipelinesCommonStatus != nil {
		in, out := &in.DataSciencePipelinesCommonStatus, &out.DataSciencePipelinesCommonStatus
		*out = new(DataSciencePipelinesCommonStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCDataSciencePipelinesStatus.
func (in *DSCDataSciencePipelinesStatus) DeepCopy() *DSCDataSciencePipelinesStatus {
	if in == nil {
		return nil
	}
	out := new(DSCDataSciencePipelinesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCFeastOperator) DeepCopyInto(out *DSCFeastOperator) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.FeastOperatorCommonSpec.DeepCopyInto(&out.FeastOperatorCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCFeastOperator.
func (in *DSCFeastOperator) DeepCopy() *DSCFeastOperator {
	if in == nil {
		return nil
	}
	out := new(DSCFeastOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCFeastOperatorStatus) DeepCopyInto(out *DSCFeastOperatorStatus) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	if in.FeastOperatorCommonStatus != nil {
		in, out := &in.FeastOperatorCommonStatus, &out.FeastOperatorCommonStatus
		*out = new(FeastOperatorCommonStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCFeastOperatorStatus.
func (in *DSCFeastOperatorStatus) DeepCopy() *DSCFeastOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(DSCFeastOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCKserve) DeepCopyInto(out *DSCKserve) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.KserveCommonSpec.DeepCopyInto(&out.KserveCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCKserve.
func (in *DSCKserve) DeepCopy() *DSCKserve {
	if in == nil {
		return nil
	}
	out := new(DSCKserve)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCKserveStatus) DeepCopyInto(out *DSCKserveStatus) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	if in.KserveCommonStatus != nil {
		in, out := &in.KserveCommonStatus, &out.KserveCommonStatus
		*out = new(KserveCommonStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCKserveStatus.
func (in *DSCKserveStatus) DeepCopy() *DSCKserveStatus {
	if in == nil {
		return nil
	}
	out := new(DSCKserveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCKueue) DeepCopyInto(out *DSCKueue) {
	*out = *in
	out.KueueManagementSpec = in.KueueManagementSpec
	in.KueueCommonSpec.DeepCopyInto(&out.KueueCommonSpec)
	out.KueueDefaultQueueSpec = in.KueueDefaultQueueSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCKueue.
func (in *DSCKueue) DeepCopy() *DSCKueue {
	if in == nil {
		return nil
	}
	out := new(DSCKueue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCKueueStatus) DeepCopyInto(out *DSCKueueStatus) {
	*out = *in
	out.KueueManagementSpec = in.KueueManagementSpec
	if in.KueueCommonStatus != nil {
		in, out := &in.KueueCommonStatus, &out.KueueCommonStatus
		*out = new(KueueCommonStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCKueueStatus.
func (in *DSCKueueStatus) DeepCopy() *DSCKueueStatus {
	if in == nil {
		return nil
	}
	out := new(DSCKueueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCLlamaStackOperator) DeepCopyInto(out *DSCLlamaStackOperator) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.LlamaStackOperatorCommonSpec.DeepCopyInto(&out.LlamaStackOperatorCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCLlamaStackOperator.
func (in *DSCLlamaStackOperator) DeepCopy() *DSCLlamaStackOperator {
	if in == nil {
		return nil
	}
	out := new(DSCLlamaStackOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCLlamaStackOperatorStatus) DeepCopyInto(out *DSCLlamaStackOperatorStatus) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	if in.LlamaStackOperatorCommonStatus != nil {
		in, out := &in.LlamaStackOperatorCommonStatus, &out.LlamaStackOperatorCommonStatus
		*out = new(LlamaStackOperatorCommonStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCLlamaStackOperatorStatus.
func (in *DSCLlamaStackOperatorStatus) DeepCopy() *DSCLlamaStackOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(DSCLlamaStackOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCModelMeshServing) DeepCopyInto(out *DSCModelMeshServing) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.ModelMeshServingCommonSpec.DeepCopyInto(&out.ModelMeshServingCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCModelMeshServing.
func (in *DSCModelMeshServing) DeepCopy() *DSCModelMeshServing {
	if in == nil {
		return nil
	}
	out := new(DSCModelMeshServing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCModelMeshServingStatus) DeepCopyInto(out *DSCModelMeshServingStatus) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	if in.ModelMeshServingCommonStatus != nil {
		in, out := &in.ModelMeshServingCommonStatus, &out.ModelMeshServingCommonStatus
		*out = new(ModelMeshServingCommonStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCModelMeshServingStatus.
func (in *DSCModelMeshServingStatus) DeepCopy() *DSCModelMeshServingStatus {
	if in == nil {
		return nil
	}
	out := new(DSCModelMeshServingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCModelRegistry) DeepCopyInto(out *DSCModelRegistry) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.ModelRegistryCommonSpec.DeepCopyInto(&out.ModelRegistryCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCModelRegistry.
func (in *DSCModelRegistry) DeepCopy() *DSCModelRegistry {
	if in == nil {
		return nil
	}
	out := new(DSCModelRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCModelRegistryStatus) DeepCopyInto(out *DSCModelRegistryStatus) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	if in.ModelRegistryCommonStatus != nil {
		in, out := &in.ModelRegistryCommonStatus, &out.ModelRegistryCommonStatus
		*out = new(ModelRegistryCommonStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCModelRegistryStatus.
func (in *DSCModelRegistryStatus) DeepCopy() *DSCModelRegistryStatus {
	if in == nil {
		return nil
	}
	out := new(DSCModelRegistryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCRay) DeepCopyInto(out *DSCRay) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.RayCommonSpec.DeepCopyInto(&out.RayCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCRay.
func (in *DSCRay) DeepCopy() *DSCRay {
	if in == nil {
		return nil
	}
	out := new(DSCRay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCRayStatus) DeepCopyInto(out *DSCRayStatus) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	if in.RayCommonStatus != nil {
		in, out := &in.RayCommonStatus, &out.RayCommonStatus
		*out = new(RayCommonStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCRayStatus.
func (in *DSCRayStatus) DeepCopy() *DSCRayStatus {
	if in == nil {
		return nil
	}
	out := new(DSCRayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCTrainingOperator) DeepCopyInto(out *DSCTrainingOperator) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.TrainingOperatorCommonSpec.DeepCopyInto(&out.TrainingOperatorCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCTrainingOperator.
func (in *DSCTrainingOperator) DeepCopy() *DSCTrainingOperator {
	if in == nil {
		return nil
	}
	out := new(DSCTrainingOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCTrainingOperatorStatus) DeepCopyInto(out *DSCTrainingOperatorStatus) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	if in.TrainingOperatorCommonStatus != nil {
		in, out := &in.TrainingOperatorCommonStatus, &out.TrainingOperatorCommonStatus
		*out = new(TrainingOperatorCommonStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCTrainingOperatorStatus.
func (in *DSCTrainingOperatorStatus) DeepCopy() *DSCTrainingOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(DSCTrainingOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCTrustyAI) DeepCopyInto(out *DSCTrustyAI) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.TrustyAICommonSpec.DeepCopyInto(&out.TrustyAICommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCTrustyAI.
func (in *DSCTrustyAI) DeepCopy() *DSCTrustyAI {
	if in == nil {
		return nil
	}
	out := new(DSCTrustyAI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCTrustyAIStatus) DeepCopyInto(out *DSCTrustyAIStatus) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	if in.TrustyAICommonStatus != nil {
		in, out := &in.TrustyAICommonStatus, &out.TrustyAICommonStatus
		*out = new(TrustyAICommonStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCTrustyAIStatus.
func (in *DSCTrustyAIStatus) DeepCopy() *DSCTrustyAIStatus {
	if in == nil {
		return nil
	}
	out := new(DSCTrustyAIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCWorkbenches) DeepCopyInto(out *DSCWorkbenches) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.WorkbenchesCommonSpec.DeepCopyInto(&out.WorkbenchesCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCWorkbenches.
func (in *DSCWorkbenches) DeepCopy() *DSCWorkbenches {
	if in == nil {
		return nil
	}
	out := new(DSCWorkbenches)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCWorkbenchesStatus) DeepCopyInto(out *DSCWorkbenchesStatus) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	if in.WorkbenchesCommonStatus != nil {
		in, out := &in.WorkbenchesCommonStatus, &out.WorkbenchesCommonStatus
		*out = new(WorkbenchesCommonStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCWorkbenchesStatus.
func (in *DSCWorkbenchesStatus) DeepCopy() *DSCWorkbenchesStatus {
	if in == nil {
		return nil
	}
	out := new(DSCWorkbenchesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dashboard) DeepCopyInto(out *Dashboard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dashboard.
func (in *Dashboard) DeepCopy() *Dashboard {
	if in == nil {
		return nil
	}
	out := new(Dashboard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dashboard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardCommonSpec) DeepCopyInto(out *DashboardCommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardCommonSpec.
func (in *DashboardCommonSpec) DeepCopy() *DashboardCommonSpec {
	if in == nil {
		return nil
	}
	out := new(DashboardCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardCommonStatus) DeepCopyInto(out *DashboardCommonStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardCommonStatus.
func (in *DashboardCommonStatus) DeepCopy() *DashboardCommonStatus {
	if in == nil {
		return nil
	}
	out := new(DashboardCommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardList) DeepCopyInto(out *DashboardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dashboard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardList.
func (in *DashboardList) DeepCopy() *DashboardList {
	if in == nil {
		return nil
	}
	out := new(DashboardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DashboardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardSpec) DeepCopyInto(out *DashboardSpec) {
	*out = *in
	in.DashboardCommonSpec.DeepCopyInto(&out.DashboardCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardSpec.
func (in *DashboardSpec) DeepCopy() *DashboardSpec {
	if in == nil {
		return nil
	}
	out := new(DashboardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardStatus) DeepCopyInto(out *DashboardStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	out.DashboardCommonStatus = in.DashboardCommonStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardStatus.
func (in *DashboardStatus) DeepCopy() *DashboardStatus {
	if in == nil {
		return nil
	}
	out := new(DashboardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSciencePipelines) DeepCopyInto(out *DataSciencePipelines) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSciencePipelines.
func (in *DataSciencePipelines) DeepCopy() *DataSciencePipelines {
	if in == nil {
		return nil
	}
	out := new(DataSciencePipelines)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataSciencePipelines) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSciencePipelinesCommonSpec) DeepCopyInto(out *DataSciencePipelinesCommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
	if in.ArgoWorkflowsControllers != nil {
		in, out := &in.ArgoWorkflowsControllers, &out.ArgoWorkflowsControllers
		*out = new(ArgoWorkflowsControllersSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSciencePipelinesCommonSpec.
func (in *DataSciencePipelinesCommonSpec) DeepCopy() *DataSciencePipelinesCommonSpec {
	if in == nil {
		return nil
	}
	out := new(DataSciencePipelinesCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSciencePipelinesCommonStatus) DeepCopyInto(out *DataSciencePipelinesCommonStatus) {
	*out = *in
	in.ComponentReleaseStatus.DeepCopyInto(&out.ComponentReleaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSciencePipelinesCommonStatus.
func (in *DataSciencePipelinesCommonStatus) DeepCopy() *DataSciencePipelinesCommonStatus {
	if in == nil {
		return nil
	}
	out := new(DataSciencePipelinesCommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSciencePipelinesList) DeepCopyInto(out *DataSciencePipelinesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataSciencePipelines, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSciencePipelinesList.
func (in *DataSciencePipelinesList) DeepCopy() *DataSciencePipelinesList {
	if in == nil {
		return nil
	}
	out := new(DataSciencePipelinesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataSciencePipelinesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSciencePipelinesSpec) DeepCopyInto(out *DataSciencePipelinesSpec) {
	*out = *in
	in.DataSciencePipelinesCommonSpec.DeepCopyInto(&out.DataSciencePipelinesCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSciencePipelinesSpec.
func (in *DataSciencePipelinesSpec) DeepCopy() *DataSciencePipelinesSpec {
	if in == nil {
		return nil
	}
	out := new(DataSciencePipelinesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSciencePipelinesStatus) DeepCopyInto(out *DataSciencePipelinesStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.DataSciencePipelinesCommonStatus.DeepCopyInto(&out.DataSciencePipelinesCommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSciencePipelinesStatus.
func (in *DataSciencePipelinesStatus) DeepCopy() *DataSciencePipelinesStatus {
	if in == nil {
		return nil
	}
	out := new(DataSciencePipelinesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeastOperator) DeepCopyInto(out *FeastOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeastOperator.
func (in *FeastOperator) DeepCopy() *FeastOperator {
	if in == nil {
		return nil
	}
	out := new(FeastOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeastOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeastOperatorCommonSpec) DeepCopyInto(out *FeastOperatorCommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeastOperatorCommonSpec.
func (in *FeastOperatorCommonSpec) DeepCopy() *FeastOperatorCommonSpec {
	if in == nil {
		return nil
	}
	out := new(FeastOperatorCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeastOperatorCommonStatus) DeepCopyInto(out *FeastOperatorCommonStatus) {
	*out = *in
	in.ComponentReleaseStatus.DeepCopyInto(&out.ComponentReleaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeastOperatorCommonStatus.
func (in *FeastOperatorCommonStatus) DeepCopy() *FeastOperatorCommonStatus {
	if in == nil {
		return nil
	}
	out := new(FeastOperatorCommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeastOperatorList) DeepCopyInto(out *FeastOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FeastOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeastOperatorList.
func (in *FeastOperatorList) DeepCopy() *FeastOperatorList {
	if in == nil {
		return nil
	}
	out := new(FeastOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeastOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeastOperatorSpec) DeepCopyInto(out *FeastOperatorSpec) {
	*out = *in
	in.FeastOperatorCommonSpec.DeepCopyInto(&out.FeastOperatorCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeastOperatorSpec.
func (in *FeastOperatorSpec) DeepCopy() *FeastOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(FeastOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeastOperatorStatus) DeepCopyInto(out *FeastOperatorStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.FeastOperatorCommonStatus.DeepCopyInto(&out.FeastOperatorCommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeastOperatorStatus.
func (in *FeastOperatorStatus) DeepCopy() *FeastOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(FeastOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kserve) DeepCopyInto(out *Kserve) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kserve.
func (in *Kserve) DeepCopy() *Kserve {
	if in == nil {
		return nil
	}
	out := new(Kserve)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kserve) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KserveCommonSpec) DeepCopyInto(out *KserveCommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
	out.Serving = in.Serving
	out.NIM = in.NIM
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KserveCommonSpec.
func (in *KserveCommonSpec) DeepCopy() *KserveCommonSpec {
	if in == nil {
		return nil
	}
	out := new(KserveCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KserveCommonStatus) DeepCopyInto(out *KserveCommonStatus) {
	*out = *in
	in.ComponentReleaseStatus.DeepCopyInto(&out.ComponentReleaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KserveCommonStatus.
func (in *KserveCommonStatus) DeepCopy() *KserveCommonStatus {
	if in == nil {
		return nil
	}
	out := new(KserveCommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KserveList) DeepCopyInto(out *KserveList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kserve, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KserveList.
func (in *KserveList) DeepCopy() *KserveList {
	if in == nil {
		return nil
	}
	out := new(KserveList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KserveList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KserveSpec) DeepCopyInto(out *KserveSpec) {
	*out = *in
	in.KserveCommonSpec.DeepCopyInto(&out.KserveCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KserveSpec.
func (in *KserveSpec) DeepCopy() *KserveSpec {
	if in == nil {
		return nil
	}
	out := new(KserveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KserveStatus) DeepCopyInto(out *KserveStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.KserveCommonStatus.DeepCopyInto(&out.KserveCommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KserveStatus.
func (in *KserveStatus) DeepCopy() *KserveStatus {
	if in == nil {
		return nil
	}
	out := new(KserveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kueue) DeepCopyInto(out *Kueue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kueue.
func (in *Kueue) DeepCopy() *Kueue {
	if in == nil {
		return nil
	}
	out := new(Kueue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kueue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueCommonSpec) DeepCopyInto(out *KueueCommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueCommonSpec.
func (in *KueueCommonSpec) DeepCopy() *KueueCommonSpec {
	if in == nil {
		return nil
	}
	out := new(KueueCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueCommonStatus) DeepCopyInto(out *KueueCommonStatus) {
	*out = *in
	in.ComponentReleaseStatus.DeepCopyInto(&out.ComponentReleaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueCommonStatus.
func (in *KueueCommonStatus) DeepCopy() *KueueCommonStatus {
	if in == nil {
		return nil
	}
	out := new(KueueCommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueDefaultQueueSpec) DeepCopyInto(out *KueueDefaultQueueSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueDefaultQueueSpec.
func (in *KueueDefaultQueueSpec) DeepCopy() *KueueDefaultQueueSpec {
	if in == nil {
		return nil
	}
	out := new(KueueDefaultQueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueList) DeepCopyInto(out *KueueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kueue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueList.
func (in *KueueList) DeepCopy() *KueueList {
	if in == nil {
		return nil
	}
	out := new(KueueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KueueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueManagementSpec) DeepCopyInto(out *KueueManagementSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueManagementSpec.
func (in *KueueManagementSpec) DeepCopy() *KueueManagementSpec {
	if in == nil {
		return nil
	}
	out := new(KueueManagementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueSpec) DeepCopyInto(out *KueueSpec) {
	*out = *in
	out.KueueManagementSpec = in.KueueManagementSpec
	in.KueueCommonSpec.DeepCopyInto(&out.KueueCommonSpec)
	out.KueueDefaultQueueSpec = in.KueueDefaultQueueSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueSpec.
func (in *KueueSpec) DeepCopy() *KueueSpec {
	if in == nil {
		return nil
	}
	out := new(KueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueStatus) DeepCopyInto(out *KueueStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.KueueCommonStatus.DeepCopyInto(&out.KueueCommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueStatus.
func (in *KueueStatus) DeepCopy() *KueueStatus {
	if in == nil {
		return nil
	}
	out := new(KueueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LlamaStackOperator) DeepCopyInto(out *LlamaStackOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LlamaStackOperator.
func (in *LlamaStackOperator) DeepCopy() *LlamaStackOperator {
	if in == nil {
		return nil
	}
	out := new(LlamaStackOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LlamaStackOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LlamaStackOperatorCommonSpec) DeepCopyInto(out *LlamaStackOperatorCommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LlamaStackOperatorCommonSpec.
func (in *LlamaStackOperatorCommonSpec) DeepCopy() *LlamaStackOperatorCommonSpec {
	if in == nil {
		return nil
	}
	out := new(LlamaStackOperatorCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LlamaStackOperatorCommonStatus) DeepCopyInto(out *LlamaStackOperatorCommonStatus) {
	*out = *in
	in.ComponentReleaseStatus.DeepCopyInto(&out.ComponentReleaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LlamaStackOperatorCommonStatus.
func (in *LlamaStackOperatorCommonStatus) DeepCopy() *LlamaStackOperatorCommonStatus {
	if in == nil {
		return nil
	}
	out := new(LlamaStackOperatorCommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LlamaStackOperatorList) DeepCopyInto(out *LlamaStackOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LlamaStackOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LlamaStackOperatorList.
func (in *LlamaStackOperatorList) DeepCopy() *LlamaStackOperatorList {
	if in == nil {
		return nil
	}
	out := new(LlamaStackOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LlamaStackOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LlamaStackOperatorSpec) DeepCopyInto(out *LlamaStackOperatorSpec) {
	*out = *in
	in.LlamaStackOperatorCommonSpec.DeepCopyInto(&out.LlamaStackOperatorCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LlamaStackOperatorSpec.
func (in *LlamaStackOperatorSpec) DeepCopy() *LlamaStackOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(LlamaStackOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LlamaStackOperatorStatus) DeepCopyInto(out *LlamaStackOperatorStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.LlamaStackOperatorCommonStatus.DeepCopyInto(&out.LlamaStackOperatorCommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LlamaStackOperatorStatus.
func (in *LlamaStackOperatorStatus) DeepCopy() *LlamaStackOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(LlamaStackOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelController) DeepCopyInto(out *ModelController) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelController.
func (in *ModelController) DeepCopy() *ModelController {
	if in == nil {
		return nil
	}
	out := new(ModelController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelController) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelControllerKerveSpec) DeepCopyInto(out *ModelControllerKerveSpec) {
	*out = *in
	out.NIM = in.NIM
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelControllerKerveSpec.
func (in *ModelControllerKerveSpec) DeepCopy() *ModelControllerKerveSpec {
	if in == nil {
		return nil
	}
	out := new(ModelControllerKerveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelControllerList) DeepCopyInto(out *ModelControllerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelController, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelControllerList.
func (in *ModelControllerList) DeepCopy() *ModelControllerList {
	if in == nil {
		return nil
	}
	out := new(ModelControllerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelControllerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelControllerMMSpec) DeepCopyInto(out *ModelControllerMMSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelControllerMMSpec.
func (in *ModelControllerMMSpec) DeepCopy() *ModelControllerMMSpec {
	if in == nil {
		return nil
	}
	out := new(ModelControllerMMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelControllerMRSpec) DeepCopyInto(out *ModelControllerMRSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelControllerMRSpec.
func (in *ModelControllerMRSpec) DeepCopy() *ModelControllerMRSpec {
	if in == nil {
		return nil
	}
	out := new(ModelControllerMRSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelControllerSpec) DeepCopyInto(out *ModelControllerSpec) {
	*out = *in
	if in.Kserve != nil {
		in, out := &in.Kserve, &out.Kserve
		*out = new(ModelControllerKerveSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelMeshServing != nil {
		in, out := &in.ModelMeshServing, &out.ModelMeshServing
		*out = new(ModelControllerMMSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelRegistry != nil {
		in, out := &in.ModelRegistry, &out.ModelRegistry
		*out = new(ModelControllerMRSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelControllerSpec.
func (in *ModelControllerSpec) DeepCopy() *ModelControllerSpec {
	if in == nil {
		return nil
	}
	out := new(ModelControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelControllerStatus) DeepCopyInto(out *ModelControllerStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelControllerStatus.
func (in *ModelControllerStatus) DeepCopy() *ModelControllerStatus {
	if in == nil {
		return nil
	}
	out := new(ModelControllerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMeshServing) DeepCopyInto(out *ModelMeshServing) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMeshServing.
func (in *ModelMeshServing) DeepCopy() *ModelMeshServing {
	if in == nil {
		return nil
	}
	out := new(ModelMeshServing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelMeshServing) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMeshServingCommonSpec) DeepCopyInto(out *ModelMeshServingCommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMeshServingCommonSpec.
func (in *ModelMeshServingCommonSpec) DeepCopy() *ModelMeshServingCommonSpec {
	if in == nil {
		return nil
	}
	out := new(ModelMeshServingCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMeshServingCommonStatus) DeepCopyInto(out *ModelMeshServingCommonStatus) {
	*out = *in
	in.ComponentReleaseStatus.DeepCopyInto(&out.ComponentReleaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMeshServingCommonStatus.
func (in *ModelMeshServingCommonStatus) DeepCopy() *ModelMeshServingCommonStatus {
	if in == nil {
		return nil
	}
	out := new(ModelMeshServingCommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMeshServingList) DeepCopyInto(out *ModelMeshServingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelMeshServing, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMeshServingList.
func (in *ModelMeshServingList) DeepCopy() *ModelMeshServingList {
	if in == nil {
		return nil
	}
	out := new(ModelMeshServingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelMeshServingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMeshServingSpec) DeepCopyInto(out *ModelMeshServingSpec) {
	*out = *in
	in.ModelMeshServingCommonSpec.DeepCopyInto(&out.ModelMeshServingCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMeshServingSpec.
func (in *ModelMeshServingSpec) DeepCopy() *ModelMeshServingSpec {
	if in == nil {
		return nil
	}
	out := new(ModelMeshServingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMeshServingStatus) DeepCopyInto(out *ModelMeshServingStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.ModelMeshServingCommonStatus.DeepCopyInto(&out.ModelMeshServingCommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMeshServingStatus.
func (in *ModelMeshServingStatus) DeepCopy() *ModelMeshServingStatus {
	if in == nil {
		return nil
	}
	out := new(ModelMeshServingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegistry) DeepCopyInto(out *ModelRegistry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegistry.
func (in *ModelRegistry) DeepCopy() *ModelRegistry {
	if in == nil {
		return nil
	}
	out := new(ModelRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelRegistry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegistryCommonSpec) DeepCopyInto(out *ModelRegistryCommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegistryCommonSpec.
func (in *ModelRegistryCommonSpec) DeepCopy() *ModelRegistryCommonSpec {
	if in == nil {
		return nil
	}
	out := new(ModelRegistryCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegistryCommonStatus) DeepCopyInto(out *ModelRegistryCommonStatus) {
	*out = *in
	in.ComponentReleaseStatus.DeepCopyInto(&out.ComponentReleaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegistryCommonStatus.
func (in *ModelRegistryCommonStatus) DeepCopy() *ModelRegistryCommonStatus {
	if in == nil {
		return nil
	}
	out := new(ModelRegistryCommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegistryList) DeepCopyInto(out *ModelRegistryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegistryList.
func (in *ModelRegistryList) DeepCopy() *ModelRegistryList {
	if in == nil {
		return nil
	}
	out := new(ModelRegistryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelRegistryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegistrySpec) DeepCopyInto(out *ModelRegistrySpec) {
	*out = *in
	in.ModelRegistryCommonSpec.DeepCopyInto(&out.ModelRegistryCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegistrySpec.
func (in *ModelRegistrySpec) DeepCopy() *ModelRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(ModelRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegistryStatus) DeepCopyInto(out *ModelRegistryStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.ModelRegistryCommonStatus.DeepCopyInto(&out.ModelRegistryCommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegistryStatus.
func (in *ModelRegistryStatus) DeepCopy() *ModelRegistryStatus {
	if in == nil {
		return nil
	}
	out := new(ModelRegistryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NimSpec) DeepCopyInto(out *NimSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NimSpec.
func (in *NimSpec) DeepCopy() *NimSpec {
	if in == nil {
		return nil
	}
	out := new(NimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ray) DeepCopyInto(out *Ray) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ray.
func (in *Ray) DeepCopy() *Ray {
	if in == nil {
		return nil
	}
	out := new(Ray)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Ray) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RayCommonSpec) DeepCopyInto(out *RayCommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RayCommonSpec.
func (in *RayCommonSpec) DeepCopy() *RayCommonSpec {
	if in == nil {
		return nil
	}
	out := new(RayCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RayCommonStatus) DeepCopyInto(out *RayCommonStatus) {
	*out = *in
	in.ComponentReleaseStatus.DeepCopyInto(&out.ComponentReleaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RayCommonStatus.
func (in *RayCommonStatus) DeepCopy() *RayCommonStatus {
	if in == nil {
		return nil
	}
	out := new(RayCommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RayList) DeepCopyInto(out *RayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Ray, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RayList.
func (in *RayList) DeepCopy() *RayList {
	if in == nil {
		return nil
	}
	out := new(RayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RaySpec) DeepCopyInto(out *RaySpec) {
	*out = *in
	in.RayCommonSpec.DeepCopyInto(&out.RayCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RaySpec.
func (in *RaySpec) DeepCopy() *RaySpec {
	if in == nil {
		return nil
	}
	out := new(RaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RayStatus) DeepCopyInto(out *RayStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.RayCommonStatus.DeepCopyInto(&out.RayCommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RayStatus.
func (in *RayStatus) DeepCopy() *RayStatus {
	if in == nil {
		return nil
	}
	out := new(RayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingOperator) DeepCopyInto(out *TrainingOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingOperator.
func (in *TrainingOperator) DeepCopy() *TrainingOperator {
	if in == nil {
		return nil
	}
	out := new(TrainingOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrainingOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingOperatorCommonSpec) DeepCopyInto(out *TrainingOperatorCommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingOperatorCommonSpec.
func (in *TrainingOperatorCommonSpec) DeepCopy() *TrainingOperatorCommonSpec {
	if in == nil {
		return nil
	}
	out := new(TrainingOperatorCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingOperatorCommonStatus) DeepCopyInto(out *TrainingOperatorCommonStatus) {
	*out = *in
	in.ComponentReleaseStatus.DeepCopyInto(&out.ComponentReleaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingOperatorCommonStatus.
func (in *TrainingOperatorCommonStatus) DeepCopy() *TrainingOperatorCommonStatus {
	if in == nil {
		return nil
	}
	out := new(TrainingOperatorCommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingOperatorList) DeepCopyInto(out *TrainingOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrainingOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingOperatorList.
func (in *TrainingOperatorList) DeepCopy() *TrainingOperatorList {
	if in == nil {
		return nil
	}
	out := new(TrainingOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrainingOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingOperatorSpec) DeepCopyInto(out *TrainingOperatorSpec) {
	*out = *in
	in.TrainingOperatorCommonSpec.DeepCopyInto(&out.TrainingOperatorCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingOperatorSpec.
func (in *TrainingOperatorSpec) DeepCopy() *TrainingOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(TrainingOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingOperatorStatus) DeepCopyInto(out *TrainingOperatorStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.TrainingOperatorCommonStatus.DeepCopyInto(&out.TrainingOperatorCommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingOperatorStatus.
func (in *TrainingOperatorStatus) DeepCopy() *TrainingOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(TrainingOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustyAI) DeepCopyInto(out *TrustyAI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustyAI.
func (in *TrustyAI) DeepCopy() *TrustyAI {
	if in == nil {
		return nil
	}
	out := new(TrustyAI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrustyAI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustyAICommonSpec) DeepCopyInto(out *TrustyAICommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
	out.Eval = in.Eval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustyAICommonSpec.
func (in *TrustyAICommonSpec) DeepCopy() *TrustyAICommonSpec {
	if in == nil {
		return nil
	}
	out := new(TrustyAICommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustyAICommonStatus) DeepCopyInto(out *TrustyAICommonStatus) {
	*out = *in
	in.ComponentReleaseStatus.DeepCopyInto(&out.ComponentReleaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustyAICommonStatus.
func (in *TrustyAICommonStatus) DeepCopy() *TrustyAICommonStatus {
	if in == nil {
		return nil
	}
	out := new(TrustyAICommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustyAIEvalSpec) DeepCopyInto(out *TrustyAIEvalSpec) {
	*out = *in
	out.LMEval = in.LMEval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustyAIEvalSpec.
func (in *TrustyAIEvalSpec) DeepCopy() *TrustyAIEvalSpec {
	if in == nil {
		return nil
	}
	out := new(TrustyAIEvalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustyAILMEvalSpec) DeepCopyInto(out *TrustyAILMEvalSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustyAILMEvalSpec.
func (in *TrustyAILMEvalSpec) DeepCopy() *TrustyAILMEvalSpec {
	if in == nil {
		return nil
	}
	out := new(TrustyAILMEvalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustyAIList) DeepCopyInto(out *TrustyAIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrustyAI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustyAIList.
func (in *TrustyAIList) DeepCopy() *TrustyAIList {
	if in == nil {
		return nil
	}
	out := new(TrustyAIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrustyAIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustyAISpec) DeepCopyInto(out *TrustyAISpec) {
	*out = *in
	in.TrustyAICommonSpec.DeepCopyInto(&out.TrustyAICommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustyAISpec.
func (in *TrustyAISpec) DeepCopy() *TrustyAISpec {
	if in == nil {
		return nil
	}
	out := new(TrustyAISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustyAIStatus) DeepCopyInto(out *TrustyAIStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.TrustyAICommonStatus.DeepCopyInto(&out.TrustyAICommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustyAIStatus.
func (in *TrustyAIStatus) DeepCopy() *TrustyAIStatus {
	if in == nil {
		return nil
	}
	out := new(TrustyAIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Workbenches) DeepCopyInto(out *Workbenches) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workbenches.
func (in *Workbenches) DeepCopy() *Workbenches {
	if in == nil {
		return nil
	}
	out := new(Workbenches)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Workbenches) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkbenchesCommonSpec) DeepCopyInto(out *WorkbenchesCommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkbenchesCommonSpec.
func (in *WorkbenchesCommonSpec) DeepCopy() *WorkbenchesCommonSpec {
	if in == nil {
		return nil
	}
	out := new(WorkbenchesCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkbenchesCommonStatus) DeepCopyInto(out *WorkbenchesCommonStatus) {
	*out = *in
	in.ComponentReleaseStatus.DeepCopyInto(&out.ComponentReleaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkbenchesCommonStatus.
func (in *WorkbenchesCommonStatus) DeepCopy() *WorkbenchesCommonStatus {
	if in == nil {
		return nil
	}
	out := new(WorkbenchesCommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkbenchesList) DeepCopyInto(out *WorkbenchesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Workbenches, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkbenchesList.
func (in *WorkbenchesList) DeepCopy() *WorkbenchesList {
	if in == nil {
		return nil
	}
	out := new(WorkbenchesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkbenchesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkbenchesSpec) DeepCopyInto(out *WorkbenchesSpec) {
	*out = *in
	in.WorkbenchesCommonSpec.DeepCopyInto(&out.WorkbenchesCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkbenchesSpec.
func (in *WorkbenchesSpec) DeepCopy() *WorkbenchesSpec {
	if in == nil {
		return nil
	}
	out := new(WorkbenchesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkbenchesStatus) DeepCopyInto(out *WorkbenchesStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.WorkbenchesCommonStatus.DeepCopyInto(&out.WorkbenchesCommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkbenchesStatus.
func (in *WorkbenchesStatus) DeepCopy() *WorkbenchesStatus {
	if in == nil {
		return nil
	}
	out := new(WorkbenchesStatus)
	in.DeepCopyInto(out)
	return out
}
