apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redhat-ods-applications

namePrefix: ai-gateway-

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/part-of: ai-gateway-operator
