apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: mcp-lifecycle-module-operator
    app.kubernetes.io/managed-by: kustomize
  name: mcp-lifecycle-module-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcp-lifecycle-module-operator-manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
