//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeFlare) DeepCopyInto(out *CodeFlare) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeFlare.
func (in *CodeFlare) DeepCopy() *CodeFlare {
	if in == nil {
		return nil
	}
	out := new(CodeFlare)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeFlare) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeFlareList) DeepCopyInto(out *CodeFlareList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CodeFlare, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeFlareList.
func (in *CodeFlareList) DeepCopy() *CodeFlareList {
	if in == nil {
		return nil
	}
	out := new(CodeFlareList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeFlareList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeFlareSpec) DeepCopyInto(out *CodeFlareSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeFlareSpec.
func (in *CodeFlareSpec) DeepCopy() *CodeFlareSpec {
	if in == nil {
		return nil
	}
	out := new(CodeFlareSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeFlareStatus) DeepCopyInto(out *CodeFlareStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeFlareStatus.
func (in *CodeFlareStatus) DeepCopy() *CodeFlareStatus {
	if in == nil {
		return nil
	}
	out := new(CodeFlareStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCDashboard) DeepCopyInto(out *DSCDashboard) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.DashboardCommonSpec.DeepCopyInto(&out.DashboardCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCDashboard.
func (in *DSCDashboard) DeepCopy() *DSCDashboard {
	if in == nil {
		return nil
	}
	out := new(DSCDashboard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCKueue) DeepCopyInto(out *DSCKueue) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.KueueCommonSpec.DeepCopyInto(&out.KueueCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCKueue.
func (in *DSCKueue) DeepCopy() *DSCKueue {
	if in == nil {
		return nil
	}
	out := new(DSCKueue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCModelRegistry) DeepCopyInto(out *DSCModelRegistry) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.ModelRegistryCommonSpec.DeepCopyInto(&out.ModelRegistryCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCModelRegistry.
func (in *DSCModelRegistry) DeepCopy() *DSCModelRegistry {
	if in == nil {
		return nil
	}
	out := new(DSCModelRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCModelRegistryStatus) DeepCopyInto(out *DSCModelRegistryStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCModelRegistryStatus.
func (in *DSCModelRegistryStatus) DeepCopy() *DSCModelRegistryStatus {
	if in == nil {
		return nil
	}
	out := new(DSCModelRegistryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCRay) DeepCopyInto(out *DSCRay) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.RayCommonSpec.DeepCopyInto(&out.RayCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCRay.
func (in *DSCRay) DeepCopy() *DSCRay {
	if in == nil {
		return nil
	}
	out := new(DSCRay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCTrainingOperator) DeepCopyInto(out *DSCTrainingOperator) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.TrainingOperatorCommonSpec.DeepCopyInto(&out.TrainingOperatorCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCTrainingOperator.
func (in *DSCTrainingOperator) DeepCopy() *DSCTrainingOperator {
	if in == nil {
		return nil
	}
	out := new(DSCTrainingOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCTrustyAI) DeepCopyInto(out *DSCTrustyAI) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
	in.TrustyAICommonSpec.DeepCopyInto(&out.TrustyAICommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCTrustyAI.
func (in *DSCTrustyAI) DeepCopy() *DSCTrustyAI {
	if in == nil {
		return nil
	}
	out := new(DSCTrustyAI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dashboard) DeepCopyInto(out *Dashboard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dashboard.
func (in *Dashboard) DeepCopy() *Dashboard {
	if in == nil {
		return nil
	}
	out := new(Dashboard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dashboard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardCommonSpec) DeepCopyInto(out *DashboardCommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardCommonSpec.
func (in *DashboardCommonSpec) DeepCopy() *DashboardCommonSpec {
	if in == nil {
		return nil
	}
	out := new(DashboardCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardList) DeepCopyInto(out *DashboardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dashboard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardList.
func (in *DashboardList) DeepCopy() *DashboardList {
	if in == nil {
		return nil
	}
	out := new(DashboardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DashboardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardSpec) DeepCopyInto(out *DashboardSpec) {
	*out = *in
	in.DashboardCommonSpec.DeepCopyInto(&out.DashboardCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardSpec.
func (in *DashboardSpec) DeepCopy() *DashboardSpec {
	if in == nil {
		return nil
	}
	out := new(DashboardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardStatus) DeepCopyInto(out *DashboardStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardStatus.
func (in *DashboardStatus) DeepCopy() *DashboardStatus {
	if in == nil {
		return nil
	}
	out := new(DashboardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSciencePipelines) DeepCopyInto(out *DataSciencePipelines) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSciencePipelines.
func (in *DataSciencePipelines) DeepCopy() *DataSciencePipelines {
	if in == nil {
		return nil
	}
	out := new(DataSciencePipelines)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataSciencePipelines) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSciencePipelinesList) DeepCopyInto(out *DataSciencePipelinesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataSciencePipelines, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSciencePipelinesList.
func (in *DataSciencePipelinesList) DeepCopy() *DataSciencePipelinesList {
	if in == nil {
		return nil
	}
	out := new(DataSciencePipelinesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataSciencePipelinesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSciencePipelinesSpec) DeepCopyInto(out *DataSciencePipelinesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSciencePipelinesSpec.
func (in *DataSciencePipelinesSpec) DeepCopy() *DataSciencePipelinesSpec {
	if in == nil {
		return nil
	}
	out := new(DataSciencePipelinesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSciencePipelinesStatus) DeepCopyInto(out *DataSciencePipelinesStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSciencePipelinesStatus.
func (in *DataSciencePipelinesStatus) DeepCopy() *DataSciencePipelinesStatus {
	if in == nil {
		return nil
	}
	out := new(DataSciencePipelinesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kserve) DeepCopyInto(out *Kserve) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kserve.
func (in *Kserve) DeepCopy() *Kserve {
	if in == nil {
		return nil
	}
	out := new(Kserve)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kserve) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KserveList) DeepCopyInto(out *KserveList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kserve, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KserveList.
func (in *KserveList) DeepCopy() *KserveList {
	if in == nil {
		return nil
	}
	out := new(KserveList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KserveList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KserveSpec) DeepCopyInto(out *KserveSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KserveSpec.
func (in *KserveSpec) DeepCopy() *KserveSpec {
	if in == nil {
		return nil
	}
	out := new(KserveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KserveStatus) DeepCopyInto(out *KserveStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KserveStatus.
func (in *KserveStatus) DeepCopy() *KserveStatus {
	if in == nil {
		return nil
	}
	out := new(KserveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kueue) DeepCopyInto(out *Kueue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kueue.
func (in *Kueue) DeepCopy() *Kueue {
	if in == nil {
		return nil
	}
	out := new(Kueue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kueue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueCommonSpec) DeepCopyInto(out *KueueCommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueCommonSpec.
func (in *KueueCommonSpec) DeepCopy() *KueueCommonSpec {
	if in == nil {
		return nil
	}
	out := new(KueueCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueList) DeepCopyInto(out *KueueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kueue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueList.
func (in *KueueList) DeepCopy() *KueueList {
	if in == nil {
		return nil
	}
	out := new(KueueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KueueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueSpec) DeepCopyInto(out *KueueSpec) {
	*out = *in
	in.KueueCommonSpec.DeepCopyInto(&out.KueueCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueSpec.
func (in *KueueSpec) DeepCopy() *KueueSpec {
	if in == nil {
		return nil
	}
	out := new(KueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueStatus) DeepCopyInto(out *KueueStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueStatus.
func (in *KueueStatus) DeepCopy() *KueueStatus {
	if in == nil {
		return nil
	}
	out := new(KueueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMeshServing) DeepCopyInto(out *ModelMeshServing) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMeshServing.
func (in *ModelMeshServing) DeepCopy() *ModelMeshServing {
	if in == nil {
		return nil
	}
	out := new(ModelMeshServing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelMeshServing) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMeshServingList) DeepCopyInto(out *ModelMeshServingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelMeshServing, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMeshServingList.
func (in *ModelMeshServingList) DeepCopy() *ModelMeshServingList {
	if in == nil {
		return nil
	}
	out := new(ModelMeshServingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelMeshServingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMeshServingSpec) DeepCopyInto(out *ModelMeshServingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMeshServingSpec.
func (in *ModelMeshServingSpec) DeepCopy() *ModelMeshServingSpec {
	if in == nil {
		return nil
	}
	out := new(ModelMeshServingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMeshServingStatus) DeepCopyInto(out *ModelMeshServingStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMeshServingStatus.
func (in *ModelMeshServingStatus) DeepCopy() *ModelMeshServingStatus {
	if in == nil {
		return nil
	}
	out := new(ModelMeshServingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegistry) DeepCopyInto(out *ModelRegistry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegistry.
func (in *ModelRegistry) DeepCopy() *ModelRegistry {
	if in == nil {
		return nil
	}
	out := new(ModelRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelRegistry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegistryCommonSpec) DeepCopyInto(out *ModelRegistryCommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegistryCommonSpec.
func (in *ModelRegistryCommonSpec) DeepCopy() *ModelRegistryCommonSpec {
	if in == nil {
		return nil
	}
	out := new(ModelRegistryCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegistryList) DeepCopyInto(out *ModelRegistryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegistryList.
func (in *ModelRegistryList) DeepCopy() *ModelRegistryList {
	if in == nil {
		return nil
	}
	out := new(ModelRegistryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelRegistryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegistrySpec) DeepCopyInto(out *ModelRegistrySpec) {
	*out = *in
	in.ModelRegistryCommonSpec.DeepCopyInto(&out.ModelRegistryCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegistrySpec.
func (in *ModelRegistrySpec) DeepCopy() *ModelRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(ModelRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegistryStatus) DeepCopyInto(out *ModelRegistryStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	out.DSCModelRegistryStatus = in.DSCModelRegistryStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegistryStatus.
func (in *ModelRegistryStatus) DeepCopy() *ModelRegistryStatus {
	if in == nil {
		return nil
	}
	out := new(ModelRegistryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ray) DeepCopyInto(out *Ray) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ray.
func (in *Ray) DeepCopy() *Ray {
	if in == nil {
		return nil
	}
	out := new(Ray)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Ray) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RayCommonSpec) DeepCopyInto(out *RayCommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RayCommonSpec.
func (in *RayCommonSpec) DeepCopy() *RayCommonSpec {
	if in == nil {
		return nil
	}
	out := new(RayCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RayList) DeepCopyInto(out *RayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Ray, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RayList.
func (in *RayList) DeepCopy() *RayList {
	if in == nil {
		return nil
	}
	out := new(RayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RaySpec) DeepCopyInto(out *RaySpec) {
	*out = *in
	in.RayCommonSpec.DeepCopyInto(&out.RayCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RaySpec.
func (in *RaySpec) DeepCopy() *RaySpec {
	if in == nil {
		return nil
	}
	out := new(RaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RayStatus) DeepCopyInto(out *RayStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RayStatus.
func (in *RayStatus) DeepCopy() *RayStatus {
	if in == nil {
		return nil
	}
	out := new(RayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingOperator) DeepCopyInto(out *TrainingOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingOperator.
func (in *TrainingOperator) DeepCopy() *TrainingOperator {
	if in == nil {
		return nil
	}
	out := new(TrainingOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrainingOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingOperatorCommonSpec) DeepCopyInto(out *TrainingOperatorCommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingOperatorCommonSpec.
func (in *TrainingOperatorCommonSpec) DeepCopy() *TrainingOperatorCommonSpec {
	if in == nil {
		return nil
	}
	out := new(TrainingOperatorCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingOperatorList) DeepCopyInto(out *TrainingOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrainingOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingOperatorList.
func (in *TrainingOperatorList) DeepCopy() *TrainingOperatorList {
	if in == nil {
		return nil
	}
	out := new(TrainingOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrainingOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingOperatorSpec) DeepCopyInto(out *TrainingOperatorSpec) {
	*out = *in
	in.TrainingOperatorCommonSpec.DeepCopyInto(&out.TrainingOperatorCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingOperatorSpec.
func (in *TrainingOperatorSpec) DeepCopy() *TrainingOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(TrainingOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingOperatorStatus) DeepCopyInto(out *TrainingOperatorStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingOperatorStatus.
func (in *TrainingOperatorStatus) DeepCopy() *TrainingOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(TrainingOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustyAI) DeepCopyInto(out *TrustyAI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustyAI.
func (in *TrustyAI) DeepCopy() *TrustyAI {
	if in == nil {
		return nil
	}
	out := new(TrustyAI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrustyAI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustyAICommonSpec) DeepCopyInto(out *TrustyAICommonSpec) {
	*out = *in
	in.DevFlagsSpec.DeepCopyInto(&out.DevFlagsSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustyAICommonSpec.
func (in *TrustyAICommonSpec) DeepCopy() *TrustyAICommonSpec {
	if in == nil {
		return nil
	}
	out := new(TrustyAICommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustyAIList) DeepCopyInto(out *TrustyAIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrustyAI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustyAIList.
func (in *TrustyAIList) DeepCopy() *TrustyAIList {
	if in == nil {
		return nil
	}
	out := new(TrustyAIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrustyAIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustyAISpec) DeepCopyInto(out *TrustyAISpec) {
	*out = *in
	in.TrustyAICommonSpec.DeepCopyInto(&out.TrustyAICommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustyAISpec.
func (in *TrustyAISpec) DeepCopy() *TrustyAISpec {
	if in == nil {
		return nil
	}
	out := new(TrustyAISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustyAIStatus) DeepCopyInto(out *TrustyAIStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustyAIStatus.
func (in *TrustyAIStatus) DeepCopy() *TrustyAIStatus {
	if in == nil {
		return nil
	}
	out := new(TrustyAIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Workbenches) DeepCopyInto(out *Workbenches) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workbenches.
func (in *Workbenches) DeepCopy() *Workbenches {
	if in == nil {
		return nil
	}
	out := new(Workbenches)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Workbenches) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkbenchesList) DeepCopyInto(out *WorkbenchesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Workbenches, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkbenchesList.
func (in *WorkbenchesList) DeepCopy() *WorkbenchesList {
	if in == nil {
		return nil
	}
	out := new(WorkbenchesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkbenchesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkbenchesSpec) DeepCopyInto(out *WorkbenchesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkbenchesSpec.
func (in *WorkbenchesSpec) DeepCopy() *WorkbenchesSpec {
	if in == nil {
		return nil
	}
	out := new(WorkbenchesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkbenchesStatus) DeepCopyInto(out *WorkbenchesStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkbenchesStatus.
func (in *WorkbenchesStatus) DeepCopy() *WorkbenchesStatus {
	if in == nil {
		return nil
	}
	out := new(WorkbenchesStatus)
	in.DeepCopyInto(out)
	return out
}
