apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-science-admingroup-maas-perses-role
  namespace: models-as-a-service #TODO: Namespace for maas perses dashboards
rules:
- apiGroups:
  - perses.dev
  resources:
  - persesdashboards
  - persesdatasources
  - perses
  verbs:
  - get
  - list