apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-science-admingroup-kuadrant-role
  namespace: kuadrant-system
rules:
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get      # gets the variable dropdown values
  - create   # allows fetching the metrics 
