apiVersion: v1
kind: ConfigMap
metadata:
  name: ogx-server-config
  labels:
    ogx.io/watch: "true"
data:
  config.yaml: |
    # OGX Server Configuration
    version: '2'
    image_name: starter
    apis:
    - inference
    providers:
      inference:
      - provider_id: ollama
        provider_type: "remote::ollama"
        config:
          url: "http://ollama-server-service.ollama-dist.svc.cluster.local:11434"
    models:
      - model_id: "llama3.2:1b"
        provider_id: ollama
        model_type: llm
    server:
      port: 8321
    storage:
      backends:
        kv_default:
          type: kv_sqlite
          db_path: ${env.SQLITE_STORE_DIR:=~/.llama/distributions/ollama}/kvstore.db
        sql_default:
          type: sql_sqlite
          db_path: ${env.SQLITE_STORE_DIR:=~/.llama/distributions/ollama}/sqlstore.db
      stores:
        metadata:
          backend: kv_default
          namespace: registry
        inference:
          backend: sql_default
          table_name: inference_store
          max_write_queue_size: 10000
          num_writers: 4
        conversations:
          backend: sql_default
          table_name: openai_conversations
        prompts:
          backend: kv_default
          namespace: prompts
---
apiVersion: ogx.io/v1beta1
kind: OGXServer
metadata:
  name: ogxserver-with-userconfig
spec:
  distribution:
    name: starter
  overrideConfig:
    name: ogx-server-config
    key: config.yaml
  network:
    port: 8321
  workload:
    overrides:
      env:
      - name: OLLAMA_EMBEDDING_MODEL
        value: all-minilm:l6-v2
