apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: model-a-hpa
        namespace: llm-d-sim
        annotations:
          llm-d.ai/epp-inference-pool: "model-a"
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: model-b-hpa
        namespace: llm-d-sim
        annotations:
          llm-d.ai/epp-inference-pool: "model-b"
