apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhods-operator
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: rhods-operator
        env:
        - name: DISABLE_DSC_CONFIG
          value: "true"
        - name: RHAI_DISABLE_DSC_RESOURCE
          value: 'true'
        - name: RHAI_DISABLE_DSCI_RESOURCE
          value: 'true'
        # In-tree components (all disabled)
        - name: RHAI_DISABLE_KUEUE_COMPONENT
          value: 'true'
        # Modules (all disabled except kserve)
        - name: RHAI_DISABLE_AIGATEWAY_MODULE
          value: 'true'
        - name: RHAI_DISABLE_AIPIPELINES_MODULE
          value: 'true'
        - name: RHAI_DISABLE_DASHBOARD_MODULE
          value: 'true'
        - name: RHAI_DISABLE_FEASTOPERATOR_MODULE
          value: 'true'
        - name: RHAI_DISABLE_MCPLIFECYCLEOPERATOR_MODULE
          value: 'true'
        - name: RHAI_DISABLE_MLFLOWOPERATOR_MODULE
          value: 'true'
        - name: RHAI_DISABLE_MODELREGISTRY_MODULE
          value: 'true'
        - name: RHAI_DISABLE_MONITORING_MODULE
          value: 'true'
        - name: RHAI_DISABLE_OGX_MODULE
          value: 'true'
        - name: RHAI_DISABLE_RAY_MODULE
          value: 'true'
        - name: RHAI_DISABLE_SPARKOPERATOR_MODULE
          value: 'true'
        - name: RHAI_DISABLE_TRAINER_MODULE
          value: 'true'
        - name: RHAI_DISABLE_TRUSTYAI_MODULE
          value: 'true'
        - name: RHAI_DISABLE_WORKBENCHES_MODULE
          value: 'true'
        # Services (all disabled except gateway)
        - name: RHAI_DISABLE_AUTH_SERVICE
          value: 'true'
        - name: RHAI_DISABLE_CERTCONFIGMAPGENERATOR_SERVICE
          value: 'true'
        - name: RHAI_DISABLE_GATEWAY_SERVICE
          value: 'false'
        - name: RHAI_DISABLE_SETUPCONTROLLER_SERVICE
          value: 'true'
        - name: RHAI_APPLICATIONS_NAMESPACE
          value: redhat-ods-applications
        - name: RHAI_VERSION
          value: REPLACE_RHAI_VERSION
        - name: ODH_PLATFORM_TYPE
          value: XKS
        - name: RHAI_CA_SECRET_NAME
          value: rhai-ca
        - name: RHAI_CA_SECRET_NAMESPACE
          value: cert-manager
        - name: RHAI_ISSUER_REF_NAME
          value: rhai-ca-issuer
        - name: RHAI_ISTIO_CA_CERTIFICATE_PATH
          value: /var/run/secrets/rhai/ca.crt
