# This patch reverts the metrics Service to plain HTTP for xKS deployments
# where service-ca is not available and --metrics-secure=false is set.
apiVersion: v1
kind: Service
metadata:
  name: redhat-ods-operator-controller-manager-metrics-service
  namespace: system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: null
spec:
  ports:
  - $patch: replace
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
