apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: opendatahub-feast-operator
  name: opendatahub-feast-metrics-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: opendatahub-feast-operator