apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: opendatahub-feast-operator
  name: {{ default (include "chart.fullname" .) .Values.serviceAccount.name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Values.namespace }}