repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.5.0
    hooks:
      - id: golangci-lint
        args: [--timeout=5m]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: gofmt -w
        language: system
        types: [go]
      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        pass_filenames: false
        types: [go]
      - id: go-unit-tests
        name: go test
        entry: make unit-test
        language: system
        pass_filenames: false
        stages: [pre-push]
