apiVersion: infrastructure.opendatahub.io/v1alpha1
kind: EKSKubernetesEngine
metadata:
  name: default-ekskubernetesengine
spec:
  dependencies:
    gatewayAPI:
      managementPolicy: Managed
    certManager:
      managementPolicy: Managed
    lws:
      managementPolicy: Managed
    sailOperator:
      managementPolicy: Managed
