apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opendatahub

resources:
- components.platform.opendatahub.io_aihubs.yaml
- manager.yaml
- rbac/

configMapGenerator:
- envs:
    - params.env
  name: model-registry-operator-parameters
generatorOptions:
  disableNameSuffixHash: true
replacements:
- path: replacements.yaml
