apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opendatahub

resources:
- components.platform.opendatahub.io_aihubs.yaml
- aihub.opendatahub.io_catalogs.yaml
- manager.yaml
- metrics_service.yaml
- monitor.yaml
- rbac/

configMapGenerator:
- envs:
    - params.env
  name: aihub-controller-parameters
generatorOptions:
  disableNameSuffixHash: true
replacements:
- path: replacements.yaml
