apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: aihub-controller-manager-metrics-tls
  labels:
    control-plane: aihub-controller-manager
    app.kubernetes.io/name: aihub-controller-manager-metrics-service
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: model-registry-operator
    app.kubernetes.io/part-of: model-registry-operator
  name: aihub-controller-manager-metrics-service
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    control-plane: aihub-controller-manager
