resources:
- manifests.yaml
- service.yaml

commonAnnotations:
  service.beta.openshift.io/inject-cabundle: "true"

configurations:
- kustomizeconfig.yaml

patches: # Or patchesStrategicMerge: depending on your Kubebuilder version/preference
  - path: patches/add_kueue_namespace_selectors.yaml
    target:
      kind: ValidatingWebhookConfiguration
      name: validating-webhook-configuration