apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../default
- ../../prometheus

patches:
- target:
    kind: Namespace
  patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: system
    $patch: delete
- target:
    kind: ServiceMonitor
    name: controller-manager-metrics-monitor
  patch: |-
    - op: replace
      path: /metadata/name
      value: mcp-lifecycle-operator-controller-manager-metrics-monitor
