---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-controller-manager
  labels:
    app.kubernetes.io/name: catalog-controller-manager
    app.kubernetes.io/component: controller
    control-plane: catalog-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: catalog-controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog-controller-manager
        app.kubernetes.io/component: controller
        control-plane: catalog-controller-manager
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      serviceAccountName: catalog-controller-manager
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      containers:
      - name: manager
        image: quay.io/opendatahub/model-registry-operator:latest
        command:
          - /manager
        args:
        - "catalog"
        - "--leader-elect"
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: RELATED_IMAGE_ODH_KUBE_RBAC_PROXY_IMAGE
            value: quay.io/openshift/origin-kube-rbac-proxy:latest
          - name: RELATED_IMAGE_POSTGRESQL_16_IMAGE
            value: quay.io/sclorg/postgresql-16-c10s:latest
          - name: RELATED_IMAGE_ODH_MODEL_METADATA_COLLECTION_IMAGE
            value: quay.io/opendatahub/odh-model-metadata-collection:latest
          - name: RELATED_IMAGE_ODH_MODEL_PERFORMANCE_DATA_IMAGE
            value: quay.io/opendatahub/odh-model-metadata-collection:latest
          - name: REGISTRIES_NAMESPACE
            value: ""
          - name: ENABLE_WEBHOOKS
            value: "true"
          - name: DEFAULT_DOMAIN
            value: ""
          - name: SKIP_MODEL_CATALOG_DB_CREATION
            value: ""
          - name: GATEWAY_DOMAIN
            value: ""
          - name: GATEWAY_NAME
            value: ""
          - name: GATEWAY_NAMESPACE
            value: ""
          - name: HTTPROUTE_NAMESPACE
            value: ""
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 10
          httpGet:
            path: /healthz
            port: 8081
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 15
          httpGet:
            path: /readyz
            port: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        - name: tmp
          mountPath: /tmp
        - name: trusted-ca
          mountPath: /etc/pki/tls/custom
          readOnly: true
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: catalog-webhook-service
      - name: tmp
        emptyDir: {}
      - name: trusted-ca
        configMap:
          name: odh-trusted-ca-bundle
          optional: true
