//nolint:testpackage // White-box tests require access to unexported functions (e.g. parseConditionsFromUnstructured).
package clusterhealth

// Generated by Claude-4.6-sonnet

import (
	"context"
	"strings"
	"testing"
	"time"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/kubernetes/scheme"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"

	"github.com/opendatahub-io/opendatahub-operator/v2/pkg/cluster/gvk"
)

func TestNamespaceConfig_List(t *testing.T) {
	tests := []struct {
		name string
		ns   NamespaceConfig
		want []string
	}{
		{"empty", NamespaceConfig{}, nil},
		{"apps only", NamespaceConfig{Apps: "my-apps"}, []string{"my-apps"}},
		{"monitoring only", NamespaceConfig{Monitoring: "my-monitoring"}, []string{"my-monitoring"}},
		{"extra only", NamespaceConfig{Extra: []string{"kube-system"}}, []string{"kube-system"}},
		{"apps and extra", NamespaceConfig{Apps: "apps", Extra: []string{"op-ns", "kube-system"}}, []string{"apps", "op-ns", "kube-system"}},
		{"apps, monitoring, extra", NamespaceConfig{Apps: "apps", Monitoring: "mon", Extra: []string{"kube-system"}}, []string{"apps", "mon", "kube-system"}},
		{"extra skips empty and whitespace", NamespaceConfig{Extra: []string{"", "  ", "valid-ns", "\t", "other"}}, []string{"valid-ns", "other"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := tt.ns.List()
			if len(got) != len(tt.want) {
				t.Errorf("List() length = %v, want %v", got, tt.want)
				return
			}
			for i := range got {
				if got[i] != tt.want[i] {
					t.Errorf("List()[%d] = %q, want %q", i, got[i], tt.want[i])
				}
			}
		})
	}
}

func TestFormatResourceList(t *testing.T) {
	tests := []struct {
		name string
		rl   corev1.ResourceList
		want string
	}{
		{"empty", corev1.ResourceList{}, ""},
		{"cpu only", corev1.ResourceList{corev1.ResourceCPU: resource.MustParse("2")}, "2000m CPU"},
		{"memory only", corev1.ResourceList{corev1.ResourceMemory: resource.MustParse("8Gi")}, "8Gi memory"},
		{"both", corev1.ResourceList{
			corev1.ResourceCPU:    resource.MustParse("4"),
			corev1.ResourceMemory: resource.MustParse("16Gi"),
		}, "4000m CPU, 16Gi memory"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := formatResourceList(tt.rl)
			if got != tt.want {
				t.Errorf("formatResourceList() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestNodeToNodeInfo(t *testing.T) {
	healthyNode := &corev1.Node{
		ObjectMeta: metav1.ObjectMeta{Name: "node-1"},
		Status: corev1.NodeStatus{
			Allocatable: corev1.ResourceList{
				corev1.ResourceCPU:    resource.MustParse("4"),
				corev1.ResourceMemory: resource.MustParse("8Gi"),
			},
			Capacity: corev1.ResourceList{
				corev1.ResourceCPU:    resource.MustParse("4"),
				corev1.ResourceMemory: resource.MustParse("8Gi"),
			},
			Conditions: []corev1.NodeCondition{
				{Type: corev1.NodeReady, Status: corev1.ConditionTrue},
				{Type: corev1.NodeMemoryPressure, Status: corev1.ConditionFalse},
			},
		},
	}
	info := nodeToNodeInfo(healthyNode)
	if info.Name != "node-1" {
		t.Errorf("Name = %q, want node-1", info.Name)
	}
	if info.UnhealthyReason != "" {
		t.Errorf("UnhealthyReason = %q, want empty for healthy node", info.UnhealthyReason)
	}
	if info.Allocatable != "4000m CPU, 8Gi memory" {
		t.Errorf("Allocatable = %q", info.Allocatable)
	}

	pressureNode := &corev1.Node{
		ObjectMeta: metav1.ObjectMeta{Name: "node-2"},
		Status: corev1.NodeStatus{
			Conditions: []corev1.NodeCondition{
				{Type: corev1.NodeMemoryPressure, Status: corev1.ConditionTrue, Message: "high"},
			},
		},
	}
	info2 := nodeToNodeInfo(pressureNode)
	if info2.UnhealthyReason == "" {
		t.Error("UnhealthyReason want non-empty for memory pressure")
	}
	if info2.UnhealthyReason != "resource pressure: NodeMemoryPressure" && info2.UnhealthyReason != "resource pressure: MemoryPressure" {
		t.Errorf("UnhealthyReason = %q", info2.UnhealthyReason)
	}

	notReadyNode := &corev1.Node{
		ObjectMeta: metav1.ObjectMeta{Name: "node-3"},
		Status: corev1.NodeStatus{
			Conditions: []corev1.NodeCondition{
				{Type: corev1.NodeReady, Status: corev1.ConditionFalse},
				{Type: corev1.NodeMemoryPressure, Status: corev1.ConditionFalse},
			},
		},
	}
	info3 := nodeToNodeInfo(notReadyNode)
	if info3.UnhealthyReason == "" {
		t.Error("UnhealthyReason want non-empty for Ready=False")
	}
	if info3.UnhealthyReason != "Ready=False" {
		t.Errorf("UnhealthyReason = %q, want Ready=False", info3.UnhealthyReason)
	}

	unknownReadyNode := &corev1.Node{
		ObjectMeta: metav1.ObjectMeta{Name: "node-4"},
		Status: corev1.NodeStatus{
			Conditions: []corev1.NodeCondition{
				{Type: corev1.NodeReady, Status: corev1.ConditionUnknown},
			},
		},
	}
	info4 := nodeToNodeInfo(unknownReadyNode)
	if info4.UnhealthyReason == "" {
		t.Error("UnhealthyReason want non-empty for Ready=Unknown")
	}
	if info4.UnhealthyReason != "Ready=Unknown" {
		t.Errorf("UnhealthyReason = %q, want Ready=Unknown", info4.UnhealthyReason)
	}
}

func TestPodUnhealthyReason(t *testing.T) {
	tests := []struct {
		name string
		info PodInfo
		want string
	}{
		{"running ready", PodInfo{Phase: "Running", Containers: []ContainerInfo{{Name: "c1", Ready: true}}}, ""},
		{"succeeded", PodInfo{Phase: "Succeeded", Containers: []ContainerInfo{}}, ""},
		{"pending", PodInfo{Phase: "Pending"}, "phase=Pending"},
		{"failed", PodInfo{Phase: "Failed"}, "phase=Failed"},
		{"running not ready", PodInfo{Phase: "Running", Containers: []ContainerInfo{{Name: "c1", Ready: false}}}, "container c1 not ready"},
		{"running restart", PodInfo{Phase: "Running", Containers: []ContainerInfo{{Name: "c1", Ready: true, RestartCount: 1}}}, "container c1 restarts=1"},
		{"running waiting", PodInfo{Phase: "Running", Containers: []ContainerInfo{{Name: "c1", Ready: true, Waiting: "CrashLoopBackOff"}}}, "container c1 waiting: CrashLoopBackOff"},
		{"running terminated", PodInfo{Phase: "Running", Containers: []ContainerInfo{{Name: "c1", Ready: true, Terminated: "Error (exit 1)"}}}, "container c1 Error (exit 1)"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := podUnhealthyReason(&tt.info)
			if got != tt.want {
				t.Errorf("podUnhealthyReason() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestQuantityExceedsOrEqual(t *testing.T) {
	tests := []struct {
		name string
		used string
		hard string
		want bool
	}{
		{"below", "1", "2", false},
		{"equal", "2", "2", true},
		{"above", "3", "2", true},
		{"zero", "0", "1", false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			used := resource.MustParse(tt.used)
			hard := resource.MustParse(tt.hard)
			got := quantityExceedsOrEqual(used, hard)
			if got != tt.want {
				t.Errorf("quantityExceedsOrEqual(%s, %s) = %v, want %v", tt.used, tt.hard, got, tt.want)
			}
		})
	}
}

func TestParseConditionsFromUnstructured(t *testing.T) {
	tests := []struct {
		name    string
		obj     map[string]interface{}
		wantN   int
		wantErr bool
	}{
		{"no status", map[string]interface{}{}, 0, false},
		{"no conditions", map[string]interface{}{"status": map[string]interface{}{}}, 0, false},
		{"one condition", map[string]interface{}{
			"status": map[string]interface{}{
				"conditions": []interface{}{
					map[string]interface{}{"type": "Ready", "status": "True", "message": "ok"},
				},
			},
		}, 1, false},
		{"two conditions", map[string]interface{}{
			"status": map[string]interface{}{
				"conditions": []interface{}{
					map[string]interface{}{"type": "A", "status": "True", "message": ""},
					map[string]interface{}{"type": "B", "status": "False", "message": "bad"},
				},
			},
		}, 2, false},
		{"malformed conditions not a slice", map[string]interface{}{
			"status": map[string]interface{}{"conditions": "not-a-slice"},
		}, 0, true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := parseConditionsFromUnstructured(tt.obj)
			if (err != nil) != tt.wantErr {
				t.Errorf("parseConditionsFromUnstructured() err = %v, wantErr %v", err, tt.wantErr)
				return
			}
			n := 0
			if got != nil {
				n = len(got)
			}
			if n != tt.wantN {
				t.Errorf("parseConditionsFromUnstructured() returned %d conditions, want %d", n, tt.wantN)
			}
		})
	}
	obj := map[string]interface{}{
		"status": map[string]interface{}{
			"conditions": []interface{}{
				map[string]interface{}{"type": "Ready", "status": "True", "message": "ok"},
			},
		},
	}
	conds, err := parseConditionsFromUnstructured(obj)
	if err != nil {
		t.Fatalf("parseConditionsFromUnstructured() err = %v", err)
	}
	if len(conds) != 1 || conds[0].Type != "Ready" || conds[0].Status != "True" || conds[0].Message != "ok" {
		t.Errorf("parseConditionsFromUnstructured() = %+v", conds)
	}
}

func TestConditionStatusIsTrue(t *testing.T) {
	for _, status := range []string{"True", "true", "TRUE"} {
		if !conditionStatusIsTrue(status) {
			t.Errorf("conditionStatusIsTrue(%q) = false, want true", status)
		}
	}
	for _, status := range []string{"False", "false", "Unknown", "", "x"} {
		if conditionStatusIsTrue(status) {
			t.Errorf("conditionStatusIsTrue(%q) = true, want false", status)
		}
	}
}

func TestRun_DSCSection_ReadyFalseReportsUnhealthy(t *testing.T) {
	sch := scheme.Scheme
	_ = corev1.AddToScheme(sch)
	_ = appsv1.AddToScheme(sch)

	// DSC is a singleton; empty name triggers discovery (list and use first).
	dsc := &unstructured.Unstructured{}
	dsc.SetGroupVersionKind(gvk.DataScienceCluster)
	dsc.SetName("default-dsc")
	dsc.Object["status"] = map[string]interface{}{
		"conditions": []interface{}{
			map[string]interface{}{"type": "Ready", "status": "False", "message": "components not ready"},
		},
	}

	cl := fake.NewClientBuilder().WithScheme(sch).WithObjects(dsc).Build()
	cfg := Config{
		Client:       cl,
		Namespaces:   NamespaceConfig{},
		Operator:     OperatorConfig{},
		DSCI:         types.NamespacedName{},
		DSC:          types.NamespacedName{}, // discover singleton
		OnlySections: []string{SectionDSC},
	}
	report, err := Run(context.Background(), cfg)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if report.DSC.Error == "" {
		t.Error("DSC section should have Error when Ready condition is False")
	}
	if !strings.Contains(report.DSC.Error, "unhealthy") {
		t.Errorf("DSC.Error should contain 'unhealthy'; got %q", report.DSC.Error)
	}
	if !strings.Contains(report.DSC.Error, "Ready=False") {
		t.Errorf("DSC.Error should contain 'Ready=False'; got %q", report.DSC.Error)
	}
}

func TestRun_DSCSection_NoInstanceFound(t *testing.T) {
	sch := scheme.Scheme
	_ = corev1.AddToScheme(sch)
	_ = appsv1.AddToScheme(sch)
	// No DSC in the cluster; discovery (empty name) should report "no DataScienceCluster found".
	cl := fake.NewClientBuilder().WithScheme(sch).Build()
	cfg := Config{
		Client:       cl,
		Namespaces:   NamespaceConfig{},
		Operator:     OperatorConfig{},
		DSCI:         types.NamespacedName{},
		DSC:          types.NamespacedName{},
		OnlySections: []string{SectionDSC},
	}
	report, err := Run(context.Background(), cfg)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if report.DSC.Error == "" {
		t.Error("DSC section should have Error when no instance exists")
	}
	if !strings.Contains(report.DSC.Error, "no DataScienceCluster found") {
		t.Errorf("DSC.Error should contain 'no DataScienceCluster found'; got %q", report.DSC.Error)
	}
}

func TestRun_DSCSection_MalformedConditionsReportsError(t *testing.T) {
	sch := scheme.Scheme
	_ = corev1.AddToScheme(sch)
	_ = appsv1.AddToScheme(sch)
	// DSC with status.conditions that is not a slice (malformed).
	dsc := &unstructured.Unstructured{}
	dsc.SetGroupVersionKind(gvk.DataScienceCluster)
	dsc.SetName("default-dsc")
	dsc.Object["status"] = map[string]interface{}{"conditions": "not-a-slice"}
	cl := fake.NewClientBuilder().WithScheme(sch).WithObjects(dsc).Build()
	cfg := Config{
		Client:       cl,
		Namespaces:   NamespaceConfig{},
		Operator:     OperatorConfig{},
		DSCI:         types.NamespacedName{},
		DSC:          types.NamespacedName{},
		OnlySections: []string{SectionDSC},
	}
	report, err := Run(context.Background(), cfg)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if report.DSC.Error == "" {
		t.Error("DSC section should have Error when status.conditions is malformed")
	}
	if !strings.Contains(report.DSC.Error, "failed to parse") {
		t.Errorf("DSC.Error should indicate parse failure; got %q", report.DSC.Error)
	}
}

func TestRun_DSCSection_RemovedComponentIgnored(t *testing.T) {
	sch := scheme.Scheme
	_ = corev1.AddToScheme(sch)
	_ = appsv1.AddToScheme(sch)
	// DSC with Kueue Removed and KueueReady=False: we should not report unhealthy for Kueue.
	// Dashboard Managed and DashboardReady=False: we should report unhealthy.
	dsc := &unstructured.Unstructured{}
	dsc.SetGroupVersionKind(gvk.DataScienceCluster)
	dsc.SetName("default-dsc")
	dsc.Object["spec"] = map[string]interface{}{
		"components": map[string]interface{}{
			"dashboard": map[string]interface{}{"managementState": "Managed"},
			"kueue":     map[string]interface{}{"managementState": "Removed"},
		},
	}
	dsc.Object["status"] = map[string]interface{}{
		"conditions": []interface{}{
			map[string]interface{}{"type": "DashboardReady", "status": "False", "message": "not ready"},
			map[string]interface{}{"type": "KueueReady", "status": "False", "message": "removed"},
		},
	}
	cl := fake.NewClientBuilder().WithScheme(sch).WithObjects(dsc).Build()
	cfg := Config{
		Client:       cl,
		DSCI:         types.NamespacedName{},
		DSC:          types.NamespacedName{},
		OnlySections: []string{SectionDSC},
	}
	report, err := Run(context.Background(), cfg)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	// Should be unhealthy due to DashboardReady=False (Kueue is Removed so we ignore KueueReady).
	if report.DSC.Error == "" {
		t.Error("DSC section should have Error when managed component Dashboard is not ready")
	}
	if !strings.Contains(report.DSC.Error, "DashboardReady=False") {
		t.Errorf("DSC.Error should contain DashboardReady=False; got %q", report.DSC.Error)
	}
	if strings.Contains(report.DSC.Error, "KueueReady") {
		t.Errorf("DSC.Error should not mention KueueReady (component is Removed); got %q", report.DSC.Error)
	}
}

func TestRun_DSCSection_RemovedComponentKeyCaseInsensitive(t *testing.T) {
	sch := scheme.Scheme
	_ = appsv1.AddToScheme(sch)
	// CR with component key "Kueue" (capital K) and Removed: we should still ignore KueueReady=False.
	dsc := &unstructured.Unstructured{}
	dsc.SetGroupVersionKind(gvk.DataScienceCluster)
	dsc.SetName("default-dsc")
	dsc.Object["spec"] = map[string]interface{}{
		"components": map[string]interface{}{
			"Kueue": map[string]interface{}{"managementState": "Removed"},
		},
	}
	dsc.Object["status"] = map[string]interface{}{
		"conditions": []interface{}{
			map[string]interface{}{"type": "KueueReady", "status": "False", "message": "removed"},
		},
	}
	cl := fake.NewClientBuilder().WithScheme(sch).WithObjects(dsc).Build()
	cfg := Config{
		Client:       cl,
		DSCI:         types.NamespacedName{},
		DSC:          types.NamespacedName{},
		OnlySections: []string{SectionDSC},
	}
	report, err := Run(context.Background(), cfg)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if strings.Contains(report.DSC.Error, "KueueReady") {
		t.Errorf("DSC.Error should not mention KueueReady when component is Removed (case-insensitive); got %q", report.DSC.Error)
	}
}

func TestRun_DSCSection_RemovedAIPipelinesV1V2Alias(t *testing.T) {
	sch := scheme.Scheme
	_ = appsv1.AddToScheme(sch)
	// v2 CR uses spec.components.aipipelines; condition can be AIPipelinesReady. Should not report when Removed.
	dsc := &unstructured.Unstructured{}
	dsc.SetGroupVersionKind(gvk.DataScienceCluster)
	dsc.SetName("default-dsc")
	dsc.Object["spec"] = map[string]interface{}{
		"components": map[string]interface{}{
			"aipipelines": map[string]interface{}{"managementState": "Removed"},
		},
	}
	dsc.Object["status"] = map[string]interface{}{
		"conditions": []interface{}{
			map[string]interface{}{"type": "AIPipelinesReady", "status": "False", "message": "removed"},
		},
	}
	cl := fake.NewClientBuilder().WithScheme(sch).WithObjects(dsc).Build()
	cfg := Config{
		Client:       cl,
		DSCI:         types.NamespacedName{},
		DSC:          types.NamespacedName{},
		OnlySections: []string{SectionDSC},
	}
	report, err := Run(context.Background(), cfg)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if strings.Contains(report.DSC.Error, "AIPipelinesReady") {
		t.Errorf("DSC.Error should not mention AIPipelinesReady when aipipelines is Removed; got %q", report.DSC.Error)
	}
	// v1 CR uses spec.components.datasciencepipelines; condition DataSciencePipelinesReady should also be ignored.
	dsc.Object["spec"] = map[string]interface{}{
		"components": map[string]interface{}{
			"datasciencepipelines": map[string]interface{}{"managementState": "Removed"},
		},
	}
	dsc.Object["status"] = map[string]interface{}{
		"conditions": []interface{}{
			map[string]interface{}{"type": "DataSciencePipelinesReady", "status": "False", "message": "removed"},
		},
	}
	cl = fake.NewClientBuilder().WithScheme(sch).WithObjects(dsc).Build()
	cfg.Client = cl
	report, err = Run(context.Background(), cfg)
	if err != nil {
		t.Fatalf("Run (v1 alias): %v", err)
	}
	if strings.Contains(report.DSC.Error, "DataSciencePipelinesReady") {
		t.Errorf("DSC.Error should not mention DataSciencePipelinesReady when datasciencepipelines is Removed; got %q", report.DSC.Error)
	}
}

func TestRun_DSCISection_DegradedReported(t *testing.T) {
	sch := scheme.Scheme
	_ = corev1.AddToScheme(sch)
	_ = appsv1.AddToScheme(sch)
	// DSCI with Degraded=True should report unhealthy; Progressing=True alone should not.
	dsci := &unstructured.Unstructured{}
	dsci.SetGroupVersionKind(gvk.DSCInitialization)
	dsci.SetName("default-dsci")
	dsci.Object["status"] = map[string]interface{}{
		"conditions": []interface{}{
			map[string]interface{}{"type": "Progressing", "status": "True", "message": "in progress"},
			map[string]interface{}{"type": "Degraded", "status": "True", "message": "something wrong"},
		},
	}
	cl := fake.NewClientBuilder().WithScheme(sch).WithObjects(dsci).Build()
	cfg := Config{
		Client:       cl,
		DSCI:         types.NamespacedName{},
		DSC:          types.NamespacedName{},
		OnlySections: []string{SectionDSCI},
	}
	report, err := Run(context.Background(), cfg)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if report.DSCI.Error == "" {
		t.Error("DSCI section should have Error when Degraded=True")
	}
	if !strings.Contains(report.DSCI.Error, "Degraded=True") {
		t.Errorf("DSCI.Error should contain Degraded=True; got %q", report.DSCI.Error)
	}
}

func TestRun_DSCISection_ProgressingIgnored(t *testing.T) {
	sch := scheme.Scheme
	_ = corev1.AddToScheme(sch)
	_ = appsv1.AddToScheme(sch)
	// DSCI with only Progressing=True (no Degraded): should not report unhealthy.
	dsci := &unstructured.Unstructured{}
	dsci.SetGroupVersionKind(gvk.DSCInitialization)
	dsci.SetName("default-dsci")
	dsci.Object["status"] = map[string]interface{}{
		"conditions": []interface{}{
			map[string]interface{}{"type": "Progressing", "status": "True", "message": "in progress"},
			map[string]interface{}{"type": "Upgradeable", "status": "False", "message": "ok"},
		},
	}
	cl := fake.NewClientBuilder().WithScheme(sch).WithObjects(dsci).Build()
	cfg := Config{
		Client:       cl,
		DSCI:         types.NamespacedName{},
		DSC:          types.NamespacedName{},
		OnlySections: []string{SectionDSCI},
	}
	report, err := Run(context.Background(), cfg)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if report.DSCI.Error != "" {
		t.Errorf("DSCI section should not report unhealthy when only Progressing/Upgradeable are set; got %q", report.DSCI.Error)
	}
}

func TestRun_NilClient(t *testing.T) {
	cfg := Config{}
	report, err := Run(context.Background(), cfg)
	if err == nil {
		t.Fatal("Run(nil client) want error")
	}
	if report != nil {
		t.Fatal("Run(nil client) want nil report")
	}
}

func TestRun_WithFakeClient(t *testing.T) {
	sch := scheme.Scheme
	_ = corev1.AddToScheme(sch)
	_ = appsv1.AddToScheme(sch)

	client := fake.NewClientBuilder().WithScheme(sch).Build()
	cfg := Config{
		Client: client,
		Namespaces: NamespaceConfig{
			Apps:  "test-apps",
			Extra: []string{"test-extra"},
		},
		Operator:     OperatorConfig{Namespace: "op-ns", Name: "op-deploy"},
		DSCI:         types.NamespacedName{Name: "default-dsci"},
		DSC:          types.NamespacedName{Name: "default-dsc"},
		OnlySections: []string{SectionNodes},
	}

	report, err := Run(context.Background(), cfg)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if report == nil {
		t.Fatal("Run: want non-nil report")
	}
	if report.Nodes.Error != "" {
		t.Errorf("Nodes.Error = %q, want empty for empty cluster", report.Nodes.Error)
	}
	if len(report.Nodes.Data.Nodes) != 0 {
		t.Errorf("Nodes.Data.Nodes length = %d, want 0", len(report.Nodes.Data.Nodes))
	}
}

func TestRun_NodesSection_UnhealthyNode(t *testing.T) {
	sch := scheme.Scheme
	_ = corev1.AddToScheme(sch)
	_ = appsv1.AddToScheme(sch)

	nodeWithPressure := &corev1.Node{
		ObjectMeta: metav1.ObjectMeta{Name: "node-1"},
		Status: corev1.NodeStatus{
			Conditions: []corev1.NodeCondition{
				{Type: corev1.NodeMemoryPressure, Status: corev1.ConditionTrue},
			},
		},
	}
	client := fake.NewClientBuilder().WithScheme(sch).WithObjects(nodeWithPressure).Build()
	cfg := Config{
		Client:       client,
		Namespaces:   NamespaceConfig{},
		OnlySections: []string{SectionNodes},
	}

	report, err := Run(context.Background(), cfg)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if report.Nodes.Error == "" {
		t.Error("Nodes.Error want non-empty when node has pressure")
	}
	if len(report.Nodes.Data.Nodes) != 1 {
		t.Errorf("Nodes.Data.Nodes length = %d, want 1", len(report.Nodes.Data.Nodes))
	}
	if report.Nodes.Data.Nodes[0].UnhealthyReason == "" {
		t.Error("node UnhealthyReason want set")
	}
	if report.Healthy() {
		t.Error("Report.Healthy() want false when node unhealthy")
	}
}

func TestRun_DeploymentsSection_NotReady(t *testing.T) {
	sch := scheme.Scheme
	_ = corev1.AddToScheme(sch)
	_ = appsv1.AddToScheme(sch)

	replicas := int32(2)
	deploy := &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{Name: "bad-deploy", Namespace: "ns1"},
		Spec:       appsv1.DeploymentSpec{Replicas: &replicas},
		Status:     appsv1.DeploymentStatus{Replicas: 2, ReadyReplicas: 1},
	}
	client := fake.NewClientBuilder().WithScheme(sch).WithObjects(deploy).Build()
	cfg := Config{
		Client:       client,
		Namespaces:   NamespaceConfig{Apps: "ns1"},
		OnlySections: []string{SectionDeployments},
	}

	report, err := Run(context.Background(), cfg)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if report.Deployments.Error == "" {
		t.Error("Deployments.Error want non-empty when deployment not ready")
	}
	if report.Healthy() {
		t.Error("Report.Healthy() want false when deployment not ready")
	}
}

func TestReport_Healthy(t *testing.T) {
	r := &Report{}
	if !r.Healthy() {
		t.Error("empty Report should be Healthy() true (no section errors)")
	}
	r.Nodes.Error = "bad"
	if r.Healthy() {
		t.Error("Report with Nodes.Error should not be Healthy()")
	}
}

func TestRun_OperatorSection_DependentOperators(t *testing.T) {
	sch := scheme.Scheme
	_ = corev1.AddToScheme(sch)
	_ = appsv1.AddToScheme(sch)

	one := int32(1)
	mainDeploy := &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{Name: "op-deploy", Namespace: "op-ns"},
		Spec: appsv1.DeploymentSpec{
			Replicas: &one,
			Selector: &metav1.LabelSelector{MatchLabels: map[string]string{"app": "op"}},
		},
		Status: appsv1.DeploymentStatus{Replicas: 1, ReadyReplicas: 1},
	}
	// OpenTelemetry operator namespace; discovery finds any deployment in the namespace
	otelDeploy := &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{Name: "opentelemetry-product", Namespace: "openshift-opentelemetry-operator"},
		Spec: appsv1.DeploymentSpec{
			Replicas: &one,
			Selector: &metav1.LabelSelector{MatchLabels: map[string]string{"app": "opentelemetry"}},
		},
		Status: appsv1.DeploymentStatus{Replicas: 1, ReadyReplicas: 1},
	}
	otelDeployUnhealthy := &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{Name: "opentelemetry-product", Namespace: "openshift-opentelemetry-operator"},
		Spec: appsv1.DeploymentSpec{
			Replicas: &one,
			Selector: &metav1.LabelSelector{MatchLabels: map[string]string{"app": "opentelemetry"}},
		},
		Status: appsv1.DeploymentStatus{Replicas: 1, ReadyReplicas: 0},
	}

	// All known dependent operator names (must match operator.go dependentOperatorNamespaces).
	allDependentNames := []string{"opentelemetry", "tempo", "cluster-observability", "kueue", "jobset", "leader-worker-set", "cert-manager", "kuadrant"}

	tests := []struct {
		name               string
		objs               []client.Object
		wantDeps           int
		wantNames          []string
		wantInstalledCount int
		wantErrContain     []string
	}{
		{
			name:               "no dependents installed - only main operator",
			objs:               []client.Object{mainDeploy},
			wantDeps:           len(allDependentNames),
			wantNames:          allDependentNames,
			wantInstalledCount: 0,
			wantErrContain:     nil,
		},
		{
			name:               "one dependent installed and healthy",
			objs:               []client.Object{mainDeploy, otelDeploy},
			wantDeps:           len(allDependentNames),
			wantNames:          allDependentNames,
			wantInstalledCount: 1,
			wantErrContain:     nil,
		},
		{
			name:               "one dependent installed but unhealthy",
			objs:               []client.Object{mainDeploy, otelDeployUnhealthy},
			wantDeps:           len(allDependentNames),
			wantNames:          allDependentNames,
			wantInstalledCount: 1,
			wantErrContain:     []string{"dependent opentelemetry"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cl := fake.NewClientBuilder().WithScheme(sch).WithObjects(tt.objs...).Build()
			cfg := Config{
				Client:       cl,
				Namespaces:   NamespaceConfig{},
				Operator:     OperatorConfig{Namespace: "op-ns", Name: "op-deploy"},
				OnlySections: []string{SectionOperator},
			}
			report, err := Run(context.Background(), cfg)
			if err != nil {
				t.Fatalf("Run: %v", err)
			}
			deps := report.Operator.Data.DependentOperators
			if len(deps) != tt.wantDeps {
				t.Errorf("DependentOperators length = %d, want %d", len(deps), tt.wantDeps)
			}
			names := make(map[string]bool)
			for _, d := range deps {
				names[d.Name] = true
			}
			for _, want := range tt.wantNames {
				if !names[want] {
					t.Errorf("DependentOperators want %q, got %v", want, names)
				}
			}
			installedCount := 0
			for _, d := range deps {
				if d.Installed {
					installedCount++
				}
			}
			if installedCount != tt.wantInstalledCount {
				t.Errorf("DependentOperators installed count = %d, want %d", installedCount, tt.wantInstalledCount)
			}
			for _, sub := range tt.wantErrContain {
				if !strings.Contains(report.Operator.Error, sub) {
					t.Errorf("Operator.Error should contain %q: %q", sub, report.Operator.Error)
				}
			}
		})
	}
}

func TestReport_PrettyPrint(t *testing.T) {
	t.Run("table header and all sections", func(t *testing.T) {
		r := &Report{CollectedAt: time.Now()}
		out := r.PrettyPrint(false)
		if !strings.Contains(out, "SECTION") || !strings.Contains(out, "STATUS") || !strings.Contains(out, "SUMMARY") {
			t.Errorf("PrettyPrint should contain table header; got:\n%s", out)
		}
		for _, name := range []string{"Nodes", "Deployments", "Pods", "Events", "Quotas", "Operator", "DSCI", "DSC"} {
			if !strings.Contains(out, name) {
				t.Errorf("PrettyPrint should contain section %q; got:\n%s", name, out)
			}
		}
	})
	t.Run("FAIL and summary when section has error", func(t *testing.T) {
		r := &Report{
			CollectedAt: time.Now(),
			Operator:    SectionResult[OperatorSection]{Error: "operator deployment not found: deployments.apps \"x\" not found"},
		}
		out := r.PrettyPrint(false)
		if !strings.Contains(out, "FAIL") {
			t.Errorf("PrettyPrint should contain FAIL when section has error; got:\n%s", out)
		}
		if !strings.Contains(out, "operator deployment not found") {
			t.Errorf("PrettyPrint summary should contain error message; got:\n%s", out)
		}
	})
	t.Run("OK and summary when section has data", func(t *testing.T) {
		r := &Report{
			CollectedAt: time.Now(),
			Nodes: SectionResult[NodesSection]{
				Data: NodesSection{Nodes: []NodeInfo{{Name: "node-1"}, {Name: "node-2"}}},
			},
		}
		out := r.PrettyPrint(false)
		if !strings.Contains(out, "OK") {
			t.Errorf("PrettyPrint should contain OK for healthy section; got:\n%s", out)
		}
		if !strings.Contains(out, "2 nodes") {
			t.Errorf("PrettyPrint Nodes summary should be '2 nodes'; got:\n%s", out)
		}
	})
	t.Run("only sections in SectionsRun are shown", func(t *testing.T) {
		r := &Report{
			CollectedAt: time.Now(),
			SectionsRun: []string{SectionNodes, SectionOperator},
			Nodes:       SectionResult[NodesSection]{Data: NodesSection{Nodes: []NodeInfo{{Name: "n1"}}}},
			Operator:    SectionResult[OperatorSection]{Data: OperatorSection{Deployment: &DeploymentInfo{Name: "op", Ready: 1, Replicas: 1}}},
		}
		out := r.PrettyPrint(false)
		if !strings.Contains(out, "Nodes") || !strings.Contains(out, "Operator") {
			t.Errorf("PrettyPrint with SectionsRun should show Nodes and Operator; got:\n%s", out)
		}
		if strings.Contains(out, "Deployments") || strings.Contains(out, "Pods") {
			t.Errorf("PrettyPrint with SectionsRun should not show Deployments or Pods; got:\n%s", out)
		}
	})
}
