package clusterhealth

// Generated by Claude-4.6-sonnet

import (
	"fmt"
	"strings"
)

const (
	statusOK   = "OK"
	statusFAIL = "FAIL"
)

// sectionRow holds one row for the pretty-print table.
type sectionRow struct {
	Section string
	Status  string
	Summary string
}

// sectionDisplayOrder is the fixed order for pretty-print; each entry is (section key, display name).
var sectionDisplayOrder = []struct{ key, display string }{
	{SectionNodes, "Nodes"},
	{SectionDeployments, "Deployments"},
	{SectionPods, "Pods"},
	{SectionEvents, "Events"},
	{SectionQuotas, "Quotas"},
	{SectionOperator, "Operator"},
	{SectionDSCI, "DSCI"},
	{SectionDSC, "DSC"},
}

// PrettyPrint returns a human-readable table of section results.
// When Report.SectionsRun is set (e.g. from -sections or -layer), only those sections are shown; otherwise all eight are shown.
// If long is true, appends a details block listing conditions and other per-item data (like ls -l).
func (r *Report) PrettyPrint(long bool) string {
	out := r.formatTable(r.sectionRows())
	if long {
		out += "\n" + r.longDetails()
	}
	return out
}

// sectionRows returns section rows in display order, optionally filtered to SectionsRun.
func (r *Report) sectionRows() []sectionRow {
	runSet := make(map[string]bool)
	for _, k := range r.SectionsRun {
		runSet[k] = true
	}
	rows := make([]sectionRow, 0, len(sectionDisplayOrder))
	for _, s := range sectionDisplayOrder {
		if len(runSet) > 0 && !runSet[s.key] {
			continue
		}
		rows = append(rows, sectionRow{
			Section: s.display,
			Status:  r.sectionStatusForKey(s.key),
			Summary: r.sectionSummaryForKey(s.key),
		})
	}
	return rows
}

func (r *Report) sectionStatusForKey(key string) string {
	switch key {
	case SectionNodes:
		return sectionStatus(r.Nodes.Error)
	case SectionDeployments:
		return sectionStatus(r.Deployments.Error)
	case SectionPods:
		return sectionStatus(r.Pods.Error)
	case SectionEvents:
		return sectionStatus(r.Events.Error)
	case SectionQuotas:
		return sectionStatus(r.Quotas.Error)
	case SectionOperator:
		return sectionStatus(r.Operator.Error)
	case SectionDSCI:
		return sectionStatus(r.DSCI.Error)
	case SectionDSC:
		return sectionStatus(r.DSC.Error)
	default:
		return statusOK
	}
}

func (r *Report) sectionSummaryForKey(key string) string {
	switch key {
	case SectionNodes:
		return r.summaryNodes()
	case SectionDeployments:
		return r.summaryDeployments()
	case SectionPods:
		return r.summaryPods()
	case SectionEvents:
		return r.summaryEvents()
	case SectionQuotas:
		return r.summaryQuotas()
	case SectionOperator:
		return r.summaryOperator()
	case SectionDSCI:
		return r.summaryDSCI()
	case SectionDSC:
		return r.summaryDSC()
	default:
		return ""
	}
}

func sectionStatus(err string) string {
	if err == "" {
		return statusOK
	}
	return statusFAIL
}

func (r *Report) summaryNodes() string {
	if r.Nodes.Error != "" {
		return truncate(r.Nodes.Error, 60)
	}
	n := len(r.Nodes.Data.Nodes)
	if n == 0 {
		return "no nodes"
	}
	unhealthy := 0
	for _, node := range r.Nodes.Data.Nodes {
		if node.UnhealthyReason != "" {
			unhealthy++
		}
	}
	if unhealthy == 0 {
		return fmt.Sprintf("%d nodes", n)
	}
	return fmt.Sprintf("%d nodes, %d unhealthy", n, unhealthy)
}

func (r *Report) summaryDeployments() string {
	if r.Deployments.Error != "" {
		return truncate(r.Deployments.Error, 60)
	}
	byNs := r.Deployments.Data.ByNamespace
	if len(byNs) == 0 {
		return "no deployments"
	}
	total, notReady := 0, 0
	for _, infos := range byNs {
		for _, d := range infos {
			total++
			if d.Replicas > 0 && d.Ready != d.Replicas {
				notReady++
			}
		}
	}
	if notReady == 0 {
		return fmt.Sprintf("%d deployments in %d namespaces", total, len(byNs))
	}
	return fmt.Sprintf("%d deployments in %d namespaces, %d not ready", total, len(byNs), notReady)
}

func (r *Report) summaryPods() string {
	if r.Pods.Error != "" {
		return truncate(r.Pods.Error, 60)
	}
	byNs := r.Pods.Data.ByNamespace
	if len(byNs) == 0 {
		return "no pods"
	}
	total, notRunning := 0, 0
	for _, infos := range byNs {
		for _, p := range infos {
			total++
			if p.Phase != "Running" {
				notRunning++
			}
		}
	}
	if notRunning == 0 {
		return fmt.Sprintf("%d pods in %d namespaces", total, len(byNs))
	}
	return fmt.Sprintf("%d pods in %d namespaces, %d not Running", total, len(byNs), notRunning)
}

func (r *Report) summaryEvents() string {
	if r.Events.Error != "" {
		return truncate(r.Events.Error, 60)
	}
	n := len(r.Events.Data.Events)
	if n == 0 {
		return "no events"
	}
	return fmt.Sprintf("%d events", n)
}

func (r *Report) summaryQuotas() string {
	if r.Quotas.Error != "" {
		return truncate(r.Quotas.Error, 60)
	}
	byNs := r.Quotas.Data.ByNamespace
	if len(byNs) == 0 {
		return "no quotas"
	}
	total, exceeded := 0, 0
	for _, infos := range byNs {
		for _, q := range infos {
			total++
			if len(q.Exceeded) > 0 {
				exceeded++
			}
		}
	}
	if exceeded == 0 {
		return fmt.Sprintf("%d quotas in %d namespaces", total, len(byNs))
	}
	return fmt.Sprintf("%d quotas in %d namespaces, %d exceeded", total, len(byNs), exceeded)
}

func (r *Report) summaryOperator() string {
	if r.Operator.Error != "" {
		return truncate(r.Operator.Error, 60)
	}
	d := r.Operator.Data.Deployment
	if d == nil {
		return "no operator deployment"
	}
	depLine := fmt.Sprintf("%s %d/%d ready", d.Name, d.Ready, d.Replicas)
	deps := r.Operator.Data.DependentOperators
	if len(deps) == 0 {
		return depLine
	}
	notInstalled := 0
	for _, dep := range deps {
		if !dep.Installed {
			notInstalled++
		}
	}
	if notInstalled == 0 {
		return fmt.Sprintf("%s, %d dependents", depLine, len(deps))
	}
	return fmt.Sprintf("%s, %d dependents (%d not installed)", depLine, len(deps), notInstalled)
}

func (r *Report) summaryDSCI() string {
	if r.DSCI.Error != "" {
		return truncate(r.DSCI.Error, 60)
	}
	name := r.DSCI.Data.Name
	if name == "" {
		return "no DSCI"
	}
	n := len(r.DSCI.Data.Conditions)
	if n == 0 {
		return name
	}
	return fmt.Sprintf("%s, %d conditions", name, n)
}

func (r *Report) summaryDSC() string {
	if r.DSC.Error != "" {
		return truncate(r.DSC.Error, 80)
	}
	name := r.DSC.Data.Name
	if name == "" {
		return "no DSC"
	}
	n := len(r.DSC.Data.Conditions)
	if n == 0 {
		return name
	}
	return fmt.Sprintf("%s, %d conditions", name, n)
}

func truncate(s string, maxLen int) string {
	s = strings.TrimSpace(s)
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}

// formatTable renders rows as a simple aligned table with a header and separator.
func (r *Report) formatTable(rows []sectionRow) string {
	const (
		colSection = 12
		colStatus  = 6
	)
	pad := func(s string, n int) string {
		if len(s) >= n {
			return s
		}
		return s + strings.Repeat(" ", n-len(s))
	}
	var b strings.Builder
	b.WriteString(pad("SECTION", colSection))
	b.WriteString("  ")
	b.WriteString(pad("STATUS", colStatus))
	b.WriteString("  SUMMARY\n")
	b.WriteString(strings.Repeat("-", colSection))
	b.WriteString("  ")
	b.WriteString(strings.Repeat("-", colStatus))
	b.WriteString("  ")
	b.WriteString("-------\n")
	for _, row := range rows {
		b.WriteString(pad(row.Section, colSection))
		b.WriteString("  ")
		b.WriteString(pad(row.Status, colStatus))
		b.WriteString("  ")
		b.WriteString(row.Summary)
		b.WriteString("\n")
	}
	return b.String()
}

// longDetails returns an expanded view of each section's data (conditions, items) when -l is used.
func (r *Report) longDetails() string {
	runSet := make(map[string]bool)
	for _, k := range r.SectionsRun {
		runSet[k] = true
	}
	var b strings.Builder
	b.WriteString("--- Details (-l) ---\n")
	for _, s := range sectionDisplayOrder {
		if len(runSet) > 0 && !runSet[s.key] {
			continue
		}
		block := r.longDetailsForSection(s.key)
		if block != "" {
			b.WriteString(s.display)
			b.WriteString(":\n")
			b.WriteString(block)
			b.WriteString("\n")
		}
	}
	return b.String()
}

func (r *Report) longDetailsForSection(key string) string {
	switch key {
	case SectionNodes:
		return r.longDetailsNodes()
	case SectionDeployments:
		return r.longDetailsDeployments()
	case SectionPods:
		return r.longDetailsPods()
	case SectionEvents:
		return r.longDetailsEvents()
	case SectionQuotas:
		return r.longDetailsQuotas()
	case SectionOperator:
		return r.longDetailsOperator()
	case SectionDSCI:
		return r.longDetailsCRConditions(r.DSCI.Data.Name, r.DSCI.Data.Conditions)
	case SectionDSC:
		return r.longDetailsCRConditions(r.DSC.Data.Name, r.DSC.Data.Conditions)
	default:
		return ""
	}
}

func (r *Report) longDetailsNodes() string {
	if r.Nodes.Error != "" {
		return "  " + r.Nodes.Error + "\n"
	}
	var b strings.Builder
	for _, n := range r.Nodes.Data.Nodes {
		status := "OK"
		if n.UnhealthyReason != "" {
			status = n.UnhealthyReason
		}
		b.WriteString("  ")
		b.WriteString(n.Name)
		b.WriteString(": ")
		b.WriteString(status)
		b.WriteString("\n")
	}
	return b.String()
}

func (r *Report) longDetailsDeployments() string {
	if r.Deployments.Error != "" {
		return "  " + r.Deployments.Error + "\n"
	}
	var b strings.Builder
	for ns, infos := range r.Deployments.Data.ByNamespace {
		for _, d := range infos {
			b.WriteString("  ")
			b.WriteString(ns)
			b.WriteString("/")
			b.WriteString(d.Name)
			b.WriteString(fmt.Sprintf(" %d/%d ready", d.Ready, d.Replicas))
			b.WriteString("\n")
		}
	}
	return b.String()
}

func (r *Report) longDetailsPods() string {
	if r.Pods.Error != "" {
		return "  " + r.Pods.Error + "\n"
	}
	var b strings.Builder
	for ns, infos := range r.Pods.Data.ByNamespace {
		for _, p := range infos {
			b.WriteString("  ")
			b.WriteString(ns)
			b.WriteString("/")
			b.WriteString(p.Name)
			b.WriteString(" ")
			b.WriteString(p.Phase)
			b.WriteString("\n")
		}
	}
	return b.String()
}

func (r *Report) longDetailsEvents() string {
	if r.Events.Error != "" {
		return "  " + r.Events.Error + "\n"
	}
	var b strings.Builder
	for _, e := range r.Events.Data.Events {
		b.WriteString("  ")
		b.WriteString(e.Namespace)
		b.WriteString("/")
		b.WriteString(e.Name)
		b.WriteString(" ")
		b.WriteString(e.Reason)
		b.WriteString(": ")
		b.WriteString(truncate(e.Message, 60))
		b.WriteString("\n")
	}
	return b.String()
}

func (r *Report) longDetailsQuotas() string {
	if r.Quotas.Error != "" {
		return "  " + r.Quotas.Error + "\n"
	}
	var b strings.Builder
	for ns, infos := range r.Quotas.Data.ByNamespace {
		for _, q := range infos {
			b.WriteString("  ")
			b.WriteString(ns)
			b.WriteString("/")
			b.WriteString(q.Name)
			if len(q.Exceeded) > 0 {
				b.WriteString(" exceeded: ")
				b.WriteString(strings.Join(q.Exceeded, ", "))
			}
			b.WriteString("\n")
		}
	}
	return b.String()
}

func (r *Report) longDetailsOperator() string {
	if r.Operator.Error != "" {
		return "  " + r.Operator.Error + "\n"
	}
	var b strings.Builder
	d := r.Operator.Data.Deployment
	if d != nil {
		b.WriteString("  ")
		b.WriteString(d.Name)
		b.WriteString(fmt.Sprintf(" %d/%d ready", d.Ready, d.Replicas))
		b.WriteString("\n")
	}
	for _, dep := range r.Operator.Data.DependentOperators {
		b.WriteString("  dependent: ")
		b.WriteString(dep.Name)
		switch {
		case !dep.Installed:
			b.WriteString(" not installed")
		case dep.Error != "":
			b.WriteString(" error: ")
			b.WriteString(dep.Error)
		case dep.Deployment != nil:
			b.WriteString(fmt.Sprintf(" %d/%d ready", dep.Deployment.Ready, dep.Deployment.Replicas))
		}
		b.WriteString("\n")
	}
	return b.String()
}

func (r *Report) longDetailsCRConditions(name string, conditions []ConditionSummary) string {
	if name == "" {
		return ""
	}
	var b strings.Builder
	for _, c := range conditions {
		b.WriteString("  ")
		b.WriteString(c.Type)
		b.WriteString(": ")
		b.WriteString(c.Status)
		if c.Message != "" {
			b.WriteString(" (")
			b.WriteString(truncate(c.Message, 50))
			b.WriteString(")")
		}
		b.WriteString("\n")
	}
	return b.String()
}
