apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - validating_webhook_configuration.yaml

commonAnnotations:
  service.beta.openshift.io/inject-cabundle: "true"

configurations:
  - kustomizeconfig.yaml
