{{- with .Values.imagePullSecrets }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lws-controller-manager
  namespace: {{ $.Values.namespace }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
