apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-lws-operator
  namespace: {{ .Values.namespace }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
