apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tls-profile-reader
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - apiservers
    verbs:
      - get
