apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- manager-configmap.yaml
- saturation-scaling-configmap.yaml
- service.yaml
- serviceaccount.yaml

images:
- name: controller
  newName: ghcr.io/llm-d/llm-d-workload-variant-autoscaler
  newTag: main
