apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: odh-tls-rule
  namespace: {{.GatewayNamespace}}
  labels:
    app.kubernetes.io/part-of: {{.GatewayName}}
spec:
  host: '*'
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 8443
      tls:
        mode: SIMPLE
        insecureSkipVerify: true
    - port:
        number: 443
      tls:
        mode: SIMPLE
        insecureSkipVerify: true