apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{.GatewayName}}
  namespace: {{.GatewayNamespace}}
  labels:
{{ toYaml .RouteLabels | indent 4 }}
  annotations:
    router.openshift.io/service-ca-certificate: "true"
    {{- if .RouteServerTimeout }}
    haproxy.router.openshift.io/timeout: {{ printf "%q" .RouteServerTimeout }}
    {{- end }}
spec:
  host: {{.GatewayHostname}}
  to:
    kind: Service
    name: {{.GatewayServiceName}}
    weight: 100
  port:
    targetPort: {{.StandardHTTPSPort}}
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
