apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redhat-ods-cloudmanager-system

resources:
- ../manager
- ../crd
- ../rbac

patches:
- path: manager_rhoai_patch.yaml
# Rename ClusterRole
- target:
    kind: ClusterRole
    name: opendatahub-azure-cloud-manager-role
  patch: |
    - op: replace
      path: /metadata/name
      value: rhods-azure-cloud-manager-role
# Rename ClusterRoleBinding and update its roleRef
- target:
    kind: ClusterRoleBinding
    name: opendatahub-azure-cloud-manager-rolebinding
  patch: |
    - op: replace
      path: /metadata/name
      value: rhods-azure-cloud-manager-rolebinding
    - op: replace
      path: /roleRef/name
      value: rhods-azure-cloud-manager-role
