apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wva-system

namePrefix: workload-variant-autoscaler-

resources:
- ../../../base/
- allow-metrics-traffic.yaml

components:
- ../../../components/openshift

configMapGenerator:
- name: wva-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true

replacements:
- source:
    kind: ConfigMap
    version: v1
    name: wva-parameters
    fieldPath: data.wva-controller-image
  targets:
  - select:
      kind: Deployment
      name: workload-variant-autoscaler-controller-manager
    fieldPaths:
    - spec.template.spec.containers.[name=manager].image

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/4/value
      value: "workload-variant-autoscaler-saturation-scaling-config"
    - op: replace
      path: /spec/template/spec/containers/0/env/5/value
      value: "workload-variant-autoscaler-manager-config"
  target:
    group: apps
    version: v1
    kind: Deployment
    name: controller-manager
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: saturation-scaling-config
      annotations:
        opendatahub.io/managed: "false"
  target:
    kind: ConfigMap
    name: saturation-scaling-config
