apiVersion: v2
name: gateway-api
description: Kubernetes Gateway API CRDs
type: application
version: 1.4.0
appVersion: "v1.4.0"
keywords:
  - gateway-api
  - crds
maintainers:
  - name: Red Hat
sources:
  - https://github.com/kubernetes-sigs/gateway-api
