apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opendatahub-eks-cloud-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opendatahub-eks-cloud-manager-role
subjects:
- kind: ServiceAccount
  name: eks-cloud-manager-operator
  namespace: system
