apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - torch-distributed.yaml
  - torch-distributed-cpu.yaml
  - torch-distributed-rocm.yaml
  - torch-distributed-cuda130-torch211-py312.yaml
  - torch-distributed-rocm714-torch211-py312.yaml
  - torch-distributed-cpu-torch211-py312.yaml
  - training-hub.yaml
  - training-hub-cpu.yaml
  - training-hub-rocm.yaml
  - training-hub-th09-cuda130-torch211-py312.yaml
  - training-hub-th09-rocm714-torch211-py312.yaml
  - training-hub-th09-cpu-torch211-py312.yaml
