//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package status

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeFlareStatus) DeepCopyInto(out *CodeFlareStatus) {
	*out = *in
	in.ComponentStatus.DeepCopyInto(&out.ComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeFlareStatus.
func (in *CodeFlareStatus) DeepCopy() *CodeFlareStatus {
	if in == nil {
		return nil
	}
	out := new(CodeFlareStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentReleaseStatus) DeepCopyInto(out *ComponentReleaseStatus) {
	*out = *in
	in.Version.DeepCopyInto(&out.Version)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentReleaseStatus.
func (in *ComponentReleaseStatus) DeepCopy() *ComponentReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentReleaseStatusMeta) DeepCopyInto(out *ComponentReleaseStatusMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentReleaseStatusMeta.
func (in *ComponentReleaseStatusMeta) DeepCopy() *ComponentReleaseStatusMeta {
	if in == nil {
		return nil
	}
	out := new(ComponentReleaseStatusMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
	if in.Releases != nil {
		in, out := &in.Releases, &out.Releases
		*out = make([]ComponentReleaseStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentsStatus) DeepCopyInto(out *ComponentsStatus) {
	*out = *in
	if in.CodeFlare != nil {
		in, out := &in.CodeFlare, &out.CodeFlare
		*out = new(CodeFlareStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Dashboard != nil {
		in, out := &in.Dashboard, &out.Dashboard
		*out = new(DashboardStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.DataSciencePipelines != nil {
		in, out := &in.DataSciencePipelines, &out.DataSciencePipelines
		*out = new(DataSciencePipelinesStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelMeshServing != nil {
		in, out := &in.ModelMeshServing, &out.ModelMeshServing
		*out = new(ModelMeshServingStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelRegistry != nil {
		in, out := &in.ModelRegistry, &out.ModelRegistry
		*out = new(ModelRegistryStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Kserve != nil {
		in, out := &in.Kserve, &out.Kserve
		*out = new(KserveStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Kueue != nil {
		in, out := &in.Kueue, &out.Kueue
		*out = new(KueueStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Ray != nil {
		in, out := &in.Ray, &out.Ray
		*out = new(RayStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.TrustyAI != nil {
		in, out := &in.TrustyAI, &out.TrustyAI
		*out = new(TrustyAIStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.TrainingOperator != nil {
		in, out := &in.TrainingOperator, &out.TrainingOperator
		*out = new(TrainingOperatorStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Workbenches != nil {
		in, out := &in.Workbenches, &out.Workbenches
		*out = new(WorkbenchesStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentsStatus.
func (in *ComponentsStatus) DeepCopy() *ComponentsStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardStatus) DeepCopyInto(out *DashboardStatus) {
	*out = *in
	in.ComponentStatus.DeepCopyInto(&out.ComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardStatus.
func (in *DashboardStatus) DeepCopy() *DashboardStatus {
	if in == nil {
		return nil
	}
	out := new(DashboardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSciencePipelinesStatus) DeepCopyInto(out *DataSciencePipelinesStatus) {
	*out = *in
	in.ComponentStatus.DeepCopyInto(&out.ComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSciencePipelinesStatus.
func (in *DataSciencePipelinesStatus) DeepCopy() *DataSciencePipelinesStatus {
	if in == nil {
		return nil
	}
	out := new(DataSciencePipelinesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KserveStatus) DeepCopyInto(out *KserveStatus) {
	*out = *in
	in.ComponentStatus.DeepCopyInto(&out.ComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KserveStatus.
func (in *KserveStatus) DeepCopy() *KserveStatus {
	if in == nil {
		return nil
	}
	out := new(KserveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueStatus) DeepCopyInto(out *KueueStatus) {
	*out = *in
	in.ComponentStatus.DeepCopyInto(&out.ComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueStatus.
func (in *KueueStatus) DeepCopy() *KueueStatus {
	if in == nil {
		return nil
	}
	out := new(KueueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMeshServingStatus) DeepCopyInto(out *ModelMeshServingStatus) {
	*out = *in
	in.ComponentStatus.DeepCopyInto(&out.ComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMeshServingStatus.
func (in *ModelMeshServingStatus) DeepCopy() *ModelMeshServingStatus {
	if in == nil {
		return nil
	}
	out := new(ModelMeshServingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegistryStatus) DeepCopyInto(out *ModelRegistryStatus) {
	*out = *in
	in.ComponentStatus.DeepCopyInto(&out.ComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegistryStatus.
func (in *ModelRegistryStatus) DeepCopy() *ModelRegistryStatus {
	if in == nil {
		return nil
	}
	out := new(ModelRegistryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RayStatus) DeepCopyInto(out *RayStatus) {
	*out = *in
	in.ComponentStatus.DeepCopyInto(&out.ComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RayStatus.
func (in *RayStatus) DeepCopy() *RayStatus {
	if in == nil {
		return nil
	}
	out := new(RayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseFileMeta) DeepCopyInto(out *ReleaseFileMeta) {
	*out = *in
	if in.Releases != nil {
		in, out := &in.Releases, &out.Releases
		*out = make([]ComponentReleaseStatusMeta, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseFileMeta.
func (in *ReleaseFileMeta) DeepCopy() *ReleaseFileMeta {
	if in == nil {
		return nil
	}
	out := new(ReleaseFileMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingOperatorStatus) DeepCopyInto(out *TrainingOperatorStatus) {
	*out = *in
	in.ComponentStatus.DeepCopyInto(&out.ComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingOperatorStatus.
func (in *TrainingOperatorStatus) DeepCopy() *TrainingOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(TrainingOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustyAIStatus) DeepCopyInto(out *TrustyAIStatus) {
	*out = *in
	in.ComponentStatus.DeepCopyInto(&out.ComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustyAIStatus.
func (in *TrustyAIStatus) DeepCopy() *TrustyAIStatus {
	if in == nil {
		return nil
	}
	out := new(TrustyAIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkbenchesStatus) DeepCopyInto(out *WorkbenchesStatus) {
	*out = *in
	in.ComponentStatus.DeepCopyInto(&out.ComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkbenchesStatus.
func (in *WorkbenchesStatus) DeepCopy() *WorkbenchesStatus {
	if in == nil {
		return nil
	}
	out := new(WorkbenchesStatus)
	in.DeepCopyInto(out)
	return out
}
