//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreWeaveKubernetesEngine) DeepCopyInto(out *CoreWeaveKubernetesEngine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreWeaveKubernetesEngine.
func (in *CoreWeaveKubernetesEngine) DeepCopy() *CoreWeaveKubernetesEngine {
	if in == nil {
		return nil
	}
	out := new(CoreWeaveKubernetesEngine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CoreWeaveKubernetesEngine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreWeaveKubernetesEngineList) DeepCopyInto(out *CoreWeaveKubernetesEngineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CoreWeaveKubernetesEngine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreWeaveKubernetesEngineList.
func (in *CoreWeaveKubernetesEngineList) DeepCopy() *CoreWeaveKubernetesEngineList {
	if in == nil {
		return nil
	}
	out := new(CoreWeaveKubernetesEngineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CoreWeaveKubernetesEngineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreWeaveKubernetesEngineSpec) DeepCopyInto(out *CoreWeaveKubernetesEngineSpec) {
	*out = *in
	out.Dependencies = in.Dependencies
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreWeaveKubernetesEngineSpec.
func (in *CoreWeaveKubernetesEngineSpec) DeepCopy() *CoreWeaveKubernetesEngineSpec {
	if in == nil {
		return nil
	}
	out := new(CoreWeaveKubernetesEngineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreWeaveKubernetesEngineStatus) DeepCopyInto(out *CoreWeaveKubernetesEngineStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreWeaveKubernetesEngineStatus.
func (in *CoreWeaveKubernetesEngineStatus) DeepCopy() *CoreWeaveKubernetesEngineStatus {
	if in == nil {
		return nil
	}
	out := new(CoreWeaveKubernetesEngineStatus)
	in.DeepCopyInto(out)
	return out
}
