apiVersion: v1
kind: Secret
metadata:
  name: epp-metrics-token
  labels:
    app.kubernetes.io/name: workload-variant-autoscaler
  annotations:
    kubernetes.io/service-account.name: epp-metrics-reader
type: kubernetes.io/service-account-token
