config:
  platform-name: OpenDataHub
  platform-version: unknown
fullnameOverride: ""
image:
  fullRef: ""
  repository: quay.io/opendatahub/odh-feast-module-operator
  tag: odh-stable
imagePullSecret: ""
leaderElect: true
nameOverride: ""
namespace: ""
replicas: 1
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 128Mi
serviceAccount:
  annotations: {}
  name: ""
upgradeGates: {}
