apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operatorNamespace }}
  annotations:
    helm.sh/resource-policy: keep
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operandNamespace }}
  annotations:
    helm.sh/resource-policy: keep
