{{- if .Values.imagePullSecrets }}
{{- $serviceAccounts := list "cert-manager" "cert-manager-cainjector" "cert-manager-webhook" }}
{{- range $serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ . }}
  namespace: {{ $.Values.operandNamespace }}
{{- with $.Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
