apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../webhook

patches:
# Add cert-manager CA injection annotations
- target:
    kind: MutatingWebhookConfiguration
  patch: |
    - op: add
      path: /metadata/annotations/cert-manager.io~1inject-ca-from
      value: opendatahub-operator-system/opendatahub-operator-webhook-serving-cert
