apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  namespace: {{ .Values.namespace }}
  version: v1.27-latest
  values:
    pilot:
      env:
        PILOT_ENABLE_GATEWAY_API: "true"
        PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER: "true"
        PILOT_ENABLE_GATEWAY_API_STATUS: "true"
        ENABLE_GATEWAY_API_INFERENCE_EXTENSION: "true"
    meshConfig:
      accessLogFile: /dev/stdout
      defaultConfig:
        proxyMetadata:
          ENABLE_GATEWAY_API_INFERENCE_EXTENSION: "true"
    {{- with .Values.imagePullSecrets }}
    global:
      imagePullSecrets:
        {{- range . }}
        - {{ .name }}
        {{- end }}
    {{- end }}
