apiVersion: v1
kind: ServiceAccount
metadata:
  name: servicemesh-operator3
  namespace: {{ .Values.namespace }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
