apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-operator-tls-profile
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - apiservers
    resourceNames:
      - cluster
    verbs:
      - get
  - apiGroups:
      - config.openshift.io
    resources:
      - apiservers
    verbs:
      - list
      - watch
