apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--watch-namespace=$(POD_NAMESPACE)"
  target:
    group: apps
    version: v1
    kind: Deployment
    name: controller-manager
