//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package common

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerConfiguration) DeepCopyInto(out *CertManagerConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerConfiguration.
func (in *CertManagerConfiguration) DeepCopy() *CertManagerConfiguration {
	if in == nil {
		return nil
	}
	out := new(CertManagerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerDependency) DeepCopyInto(out *CertManagerDependency) {
	*out = *in
	out.Configuration = in.Configuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerDependency.
func (in *CertManagerDependency) DeepCopy() *CertManagerDependency {
	if in == nil {
		return nil
	}
	out := new(CertManagerDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dependencies) DeepCopyInto(out *Dependencies) {
	*out = *in
	out.CertManager = in.CertManager
	out.LWS = in.LWS
	out.SailOperator = in.SailOperator
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dependencies.
func (in *Dependencies) DeepCopy() *Dependencies {
	if in == nil {
		return nil
	}
	out := new(Dependencies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LWSConfiguration) DeepCopyInto(out *LWSConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LWSConfiguration.
func (in *LWSConfiguration) DeepCopy() *LWSConfiguration {
	if in == nil {
		return nil
	}
	out := new(LWSConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LWSDependency) DeepCopyInto(out *LWSDependency) {
	*out = *in
	out.Configuration = in.Configuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LWSDependency.
func (in *LWSDependency) DeepCopy() *LWSDependency {
	if in == nil {
		return nil
	}
	out := new(LWSDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SailOperatorConfiguration) DeepCopyInto(out *SailOperatorConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SailOperatorConfiguration.
func (in *SailOperatorConfiguration) DeepCopy() *SailOperatorConfiguration {
	if in == nil {
		return nil
	}
	out := new(SailOperatorConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SailOperatorDependency) DeepCopyInto(out *SailOperatorDependency) {
	*out = *in
	out.Configuration = in.Configuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SailOperatorDependency.
func (in *SailOperatorDependency) DeepCopy() *SailOperatorDependency {
	if in == nil {
		return nil
	}
	out := new(SailOperatorDependency)
	in.DeepCopyInto(out)
	return out
}
