apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maas-controller-secret-migrate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: maas-controller-secret-migrate
subjects:
- kind: ServiceAccount
  name: maas-controller
  namespace: opendatahub
