apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: maas-controller-secret-migrate
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["maas-db-config"]
  verbs: ["get"]
