apiVersion: infrastructure.opendatahub.io/v1alpha1
kind: CoreWeaveKubernetesEngine
metadata:
  name: default-coreweavekubernetesengine
spec:
  dependencies:
    gatewayAPI:
      managementPolicy: Managed
    certManager:
      managementPolicy: Managed
    lws:
      managementPolicy: Managed
      configuration:
        namespace: openshift-lws-operator
    sailOperator:
      managementPolicy: Managed
      configuration:
        namespace: istio-system
