apiVersion: v1
kind: Service
metadata:
  name: dev-model-service
  namespace: llm-d-sim
  labels:
    app: dev-model-decode
    llm-d.ai/inferenceServing: "true"
spec:
  selector:
    app: dev-model-decode
    llm-d.ai/inferenceServing: "true"
  ports:
    - name: http
      port: 8000
      protocol: TCP
  type: ClusterIP
