---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - limitranges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - kubeflow-trainer-cache-initializer
  - kubeflow-trainer-controller-manager
  resources:
  - serviceaccounts
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - components.platform.opendatahub.io
  resources:
  - trainers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - components.platform.opendatahub.io
  resources:
  - trainers/finalizers
  verbs:
  - update
- apiGroups:
  - components.platform.opendatahub.io
  resources:
  - trainers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.openshift.io
  resources:
  - apiservers
  - clusterversions
  verbs:
  - get
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jobset.x-k8s.io
  resources:
  - jobsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - node.k8s.io
  resources:
  - runtimeclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - jobsetoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - operatorconditions
  verbs:
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - kubeflow-trainer-controller-manager
  - kubeflow-trainer-view
  resources:
  - clusterrolebindings
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - kubeflow-trainer-admin
  - kubeflow-trainer-cache-initializer
  - kubeflow-trainer-controller-manager
  - kubeflow-trainer-edit
  - kubeflow-trainer-view
  - training-admin
  - training-edit
  - training-view
  resources:
  - clusterroles
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - kubeflow-trainer-cache-initializer
  - kubeflow-trainer-public
  resources:
  - rolebindings
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - kubeflow-trainer-public
  resources:
  - roles
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - scheduling.volcano.sh
  - scheduling.x-k8s.io
  resources:
  - podgroups
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - trainer.kubeflow.org
  resources:
  - clustertrainingruntimes
  - trainingruntimes
  - trainjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - trainer.kubeflow.org
  resources:
  - clustertrainingruntimes/finalizers
  - trainingruntimes/finalizers
  - trainjobs/finalizers
  - trainjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - trainer.kubeflow.org
  resources:
  - clustertrainingruntimes/status
  - trainingruntimes/status
  verbs:
  - get
