apiVersion: apps/v1
kind: Deployment
metadata:
  name: coreweave-cloud-manager-operator
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: RHAI_OPERATOR_NAMESPACE
          value: redhat-ods-operator
        - name: RHAI_WEBHOOK_CERT_SECRET_NAME
          value: rhai-operator-controller-webhook-cert
        - name: RHAI_WEBHOOK_SERVICE_NAME
          value: rhai-operator-webhook-service
        - name: RHAI_WEBHOOK_CERT_NAME
          value: rhai-operator-webhook-cert
        - name: RHAI_CA_SECRET_NAME
          value: rhaii-ca
        - name: RHAI_ISSUER_REF_NAME
          value: rhaii-ca-issuer
