apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: system
  labels:
    app.kubernetes.io/name: ai-gateway-operator
data:
  platform-type: "OpenDataHub"
  platform-version: "unknown"
