apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    # Points to the component repo where the PR is opened
    build.appstudio.openshift.io/repo: https://github.com/opendatahub-io/opendatahub-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[issue_comment]"
    pipelinesascode.tekton.dev/on-comment: "^/early-gate"
  labels:
    appstudio.openshift.io/application: opendatahub-builds
    appstudio.openshift.io/component: early-gate-test
    pipelines.appstudio.openshift.io/type: build
  name: early-gate-test-on-comment
  namespace: open-data-hub-tenant
spec:
  params:
  - name: group-components
    value: '{ "odh-operator-ci": "opendatahub/opendatahub-operator" }'
  - name: operator-git-url
    value: 'https://github.com/opendatahub-io/opendatahub-operator'
  - name: operator-revision
    value: 'main'
  - name: operator-output-image
    value: quay.io/opendatahub/opendatahub-operator:odh-pr-{{revision}}
  - name: bundle-output-image
    value: quay.io/opendatahub/opendatahub-operator-bundle:odh-pr-{{revision}}
  - name: catalog-output-image
    value: quay.io/opendatahub/opendatahub-operator-catalog:odh-pr-{{revision}}
  - name: operator-dockerfile
    value: Dockerfiles/rhoai.Dockerfile
  - name: build-version-tag
    value: "odh-stable"
  - name: operator-build-args
    value:
    - BUILD_TYPE=CI
  - name: pipeline-type
    value: "pull-request"
  - name: image-expires-after
    value: "7d"
  - name: build-config-git-url
    value: "https://github.com/opendatahub-io/ODH-Build-Config"
  - name: build-config-revision
    value: "main"
  - name: openshift-version
    value: "v4.20"
  - name: quay-tag
    value: "odh-stable"
  - name: utils-repo-url
    value: "https://github.com/red-hat-data-services/RHOAI-Konflux-Automation.git"
  - name: utils-repo-ref
    value: "odh"
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/opendatahub-io/odh-konflux-central.git
    - name: revision
      value: 'earlygate'
    - name: pathInRepo
      value: e2e-early-gate/early-gate-operator-pipeline.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-odh-feast-operator
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
