# permissions for end users to administer NeMo-Guardrails.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nemoguardrail-admin-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.authorization.k8s.io/aggregate-to-nemoguardrail-admin-role: "true"
rules:
  []
---
# permissions for end users to edit NeMo-Guardrails.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: trustyai-service-operator
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-nemoguardrail-admin-role: "true"
  name: nemoguardrail-editor-role
rules:
  - apiGroups:
      - trustyai.opendatahub.io
    resources:
      - nemoguardrails
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
# permissions for end users to view NeMo-Guardrails.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: trustyai-service-operator
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: nemoguardrail-viewer-role
rules:
  - apiGroups:
      - trustyai.opendatahub.io
    resources:
      - nemoguardrails
      - nemoguardrails/status
      - nemoguardrails/finalizers
    verbs:
      - get
      - list
      - watch
