# This rule is not used by the ogx-module itself.
# It is provided to allow cluster admins to manage access to the OGX module CR.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: components-ogx-admin-role
  labels:
    app.kubernetes.io/name: opendatahub-ogx-operator
rules:
  - apiGroups:
      - components.platform.opendatahub.io
    resources:
      - ogxs
    verbs:
      - "*"
  - apiGroups:
      - components.platform.opendatahub.io
    resources:
      - ogxs/status
    verbs:
      - get
