apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: ogx-k8s-operator-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: ogx-k8s-operator-

resources:
- ../crd
- ../rbac
- ../manager
- ../webhook

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: ogx-k8s-operator

# Labels to add to all resources and selectors.

# [PROMETHEUS] To enable prometheus monitor, uncomment all sections with 'PROMETHEUS'.
#- ../prometheus

patches:
- path: manager_webhook_patch.yaml

# Mount the controller config file for loading manager configurations
# through a ComponentConfig type
#- manager_config_patch.yaml
