apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opendatahub-ogx-system

namePrefix: opendatahub-ogx-

resources:
  - ../crd
  - ../rbac
  - ../manager
  - metrics_service.yaml

patches:
  - path: manager_metrics_patch.yaml
    target:
      kind: Deployment
