apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: training-hub-universal-rocm
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/opendatahub-io/distributed-workloads/tree/main/images/universal/training"
    opendatahub.io/notebook-image-name: "Training | Jupyter | PyTorch | ROCm | Python"
    opendatahub.io/notebook-image-desc: "Training runtime image for ROCm GPU-based fine-tuning and distributed training."
    opendatahub.io/notebook-image-order: "3"
    opendatahub.io/recommended-accelerators: '["amd.com/gpu"]'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "3.4"
      annotations:
        opendatahub.io/workbench-image-recommended: 'false'
        opendatahub.io/notebook-build-commit: a66ec72
        opendatahub.io/notebook-software: |
          [
            {"name": "ROCm", "version": "6.4"},
            {"name": "Python", "version": "v3.12"},
            {"name": "PyTorch", "version": "2.9.1"},
            {"name": "Training Hub", "version": "v0.6.0"}
          ]
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "transformers", "version": "4.57.6"},
            {"name": "accelerate", "version": "1.12.0"},
            {"name": "peft", "version": "0.18.1"},
            {"name": "trl", "version": "0.24.0"},
            {"name": "deepspeed", "version": "0.18.9"},
            {"name": "flash-attn", "version": "2.8.3"},
            {"name": "triton", "version": "3.5.1"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/odh-th06-rocm64-torch291-py312
      from:
        kind: DockerImage
        name: quay.io/opendatahub/odh-th06-rocm64-torch291-py312:odh-3.4
      referencePolicy:
        type: Source
    - name: "3.5"
      annotations:
        opendatahub.io/workbench-image-recommended: 'true'
        opendatahub.io/notebook-build-commit: a66ec72
        opendatahub.io/notebook-software: |
          [
            {"name": "ROCm", "version": "6.4"},
            {"name": "Python", "version": "v3.12"},
            {"name": "PyTorch", "version": "2.9.1"},
            {"name": "Training Hub", "version": "v0.6.0"}
          ]
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "transformers", "version": "4.57.6"},
            {"name": "accelerate", "version": "1.12.0"},
            {"name": "peft", "version": "0.18.1"},
            {"name": "trl", "version": "0.24.0"},
            {"name": "deepspeed", "version": "0.18.9"},
            {"name": "flash-attn", "version": "2.8.3"},
            {"name": "triton", "version": "3.5.1"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/odh-th06-rocm64-torch291-py312
      from:
        kind: DockerImage
        name: quay.io/opendatahub/odh-th06-rocm64-torch291-py312:odh-3.5-ea1
      referencePolicy:
        type: Source
