apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: authorino-operator-clusterrolebinding
  namespace: {{ .Values.operatorNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: authorino-operator-clusterrole
subjects:
  - kind: ServiceAccount
    name: authorino-operator
    namespace: {{ .Values.operatorNamespace }}
