apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: limitador-operator-controller-manager-clusterrolebinding
  namespace: {{ .Values.operatorNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: limitador-operator-controller-manager-clusterrole
subjects:
  - kind: ServiceAccount
    name: limitador-operator-controller-manager
    namespace: {{ .Values.operatorNamespace }}
