apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: authorino-operator
  name: authorino-operator
  namespace: {{ .Values.operatorNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: authorino-operator
  template:
    metadata:
      labels:
        control-plane: authorino-operator
      namespace: {{ .Values.operatorNamespace }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - args:
            - --leader-elect
          command:
            - /manager
          env:
            - name: RELATED_IMAGE_AUTHORINO
              value: registry.redhat.io/rhcl-1/authorino-rhel9@sha256:c2208382e16c501e4ed58aea83f54d108567f36853cf79f7ffdf8ee54ff4ace8
          image: registry.redhat.io/rhcl-1/authorino-rhel9-operator@sha256:4e581c0172549df72c6ef8978e96d771645bc36298d2ccf9240af4e71c088733
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          ports:
            - containerPort: 8080
              name: metrics
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 200m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
      securityContext:
        runAsNonRoot: true
      serviceAccountName: authorino-operator
      terminationGracePeriodSeconds: 10
