{{- if .Values.imagePullSecret.dockerConfigJson }}
{{- $namespaces := list .Values.operatorNamespace .Values.operandNamespace | uniq }}
{{- range $ns := $namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.imagePullSecret.name }}
  namespace: {{ $ns }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $.Values.imagePullSecret.dockerConfigJson | b64enc }}
{{- end }}
{{- end }}
