apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: dns-operator-controller-manager
  name: dns-operator-controller-manager-metrics-service
  namespace: {{ .Values.operatorNamespace }}
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
    - name: pprof
      port: 8082
      targetPort: pprof
  selector:
    control-plane: dns-operator-controller-manager
