apiVersion: v1
kind: ServiceAccount
metadata:
  name: authorino-operator
  namespace: {{ .Values.operatorNamespace }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
