apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: {{ .Values.operandNamespace }}
  annotations:
    helm.sh/resource-policy: keep
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
