apiVersion: v1
kind: ServiceAccount
metadata:
  name: authorino-authorino
  namespace: {{ .Values.operandNamespace }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
