apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-registry-operator-controller-manager-metrics-monitor
  namespace: system
spec:
  selector:
    matchLabels:
      control-plane: model-registry-operator
