name: Post-Codefreeze Gatekeeper

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled]
    branches:
      - 'rhoai-3.5'
jobs:
  post-codefreeze-gate:
    if: github.event.action != 'labeled' || github.event.label.name == 'run-gatekeeper'
    uses: red-hat-data-services/devops-shared-resources/.github/workflows/post-codefreeze-gate-logic.yml@gatekeeper
    secrets: inherit
