name: Check config and readme updates
on:
  pull_request:
jobs:
  file-updates:
    name: Ensure generated files are included
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Save the PR number for artifact upload
        run: |
          echo ${{ github.event.number }} > pr_number.txt
      - name: Upload the PR number as artifact
        id: artifact-upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: pr_number
          path: ./pr_number.txt
          retention-days: 1 # This will delete the generated artifacts every day.
      - name: Generate files
        run: make generate manifests-all api-docs
      - name: Ensure generated files are up-to-date
        id: check_generated_files
        run : |
          rm ./pr_number.txt # remove the pr_number.txt before checking "git status", to have correct assessment of the changed files.
          if [[ -n $(git status -s) ]]
          then
            echo "Generated files have been missed in the PR"
            git diff
           exit 1
          else
            echo "No new files to commit"
          fi
