name: Unit Tests
on:
  push:
    branches:
      - rhoai
      - main
  pull_request:
      paths:
      - 'internal/**'
      - 'pkg/**'
      - 'cmd/main.go'
      - 'api/**'
      - 'config/**'

jobs:
  unit-test:
    name: Run tests and collect coverage on internal and pkg
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Run Unit Tests
        env:
          TEST_SRC: ./internal/... ./pkg/... ./api/services/v1alpha1/...
        run: |
          make manifests-all
          make get-manifests
          make unit-test

      - name: Upload results to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
