name: Unit Tests
on:
  push:
    branches:
      - rhoai
      - main
  pull_request:
      paths:
      - 'internal/**'
      - 'pkg/**'
      - 'cmd/main.go'
      - 'api/**'
      - 'config/**'

jobs:
  unit-test:
    name: Run tests and collect coverage on internal and pkg
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod

      - name: Run Unit Tests
        env:
          TEST_SRC: ./internal/... ./pkg/... ./api/services/v1alpha1/...
        run: |
          make manifests-all
          make get-manifests
          make unit-test

      - name: Upload results to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
