name: Run prometheus unit tests
on:
  pull_request:
    paths:
      - 'internal/controller/components/**/monitoring/*-prometheusrules.tmpl.yaml'
      - 'internal/controller/components/**/monitoring/*-alerting.unit-tests.yaml'
      - 'tests/prometheus_unit_tests/scripts/**'
      - 'Makefile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Setup Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: go.mod
    - name: Install Promtool
      run: |
        sudo apt-get update && sudo apt-get install -y prometheus
    - name: Run prometheus-unit-tests
      run : make test-alerts
